package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TBranchfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_name
     *
     * @mbggenerated
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_man
     *
     * @mbggenerated
     */
    private String branchMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_address
     *
     * @mbggenerated
     */
    private String branchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_zip
     *
     * @mbggenerated
     */
    private String branchZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_email
     *
     * @mbggenerated
     */
    private String branchEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_tel
     *
     * @mbggenerated
     */
    private String branchTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_fax
     *
     * @mbggenerated
     */
    private String branchFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_memo
     *
     * @mbggenerated
     */
    private String branchMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.Store_type
     *
     * @mbggenerated
     */
    private String storeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.is_init
     *
     * @mbggenerated
     */
    private String isInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.init_date
     *
     * @mbggenerated
     */
    private Date initDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.is_logout
     *
     * @mbggenerated
     */
    private String isLogout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.logout_date
     *
     * @mbggenerated
     */
    private Date logoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_IsConnect
     *
     * @mbggenerated
     */
    private String serverIsconnect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_domain
     *
     * @mbggenerated
     */
    private String serverDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_port
     *
     * @mbggenerated
     */
    private Integer serverPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_pwd
     *
     * @mbggenerated
     */
    private String serverPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_save
     *
     * @mbggenerated
     */
    private String isshareSave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_integral
     *
     * @mbggenerated
     */
    private String isshareIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_ret
     *
     * @mbggenerated
     */
    private String isshareRet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_give
     *
     * @mbggenerated
     */
    private String isshareGive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_zero
     *
     * @mbggenerated
     */
    private String isshareZero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_class
     *
     * @mbggenerated
     */
    private String branchClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.price_type
     *
     * @mbggenerated
     */
    private String priceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_limit
     *
     * @mbggenerated
     */
    private String isshareLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_pwd
     *
     * @mbggenerated
     */
    private String branchPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_user
     *
     * @mbggenerated
     */
    private String serverUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.price_mode
     *
     * @mbggenerated
     */
    private String priceMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.zb_sup_settle
     *
     * @mbggenerated
     */
    private String zbSupSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.zb_cust_settle
     *
     * @mbggenerated
     */
    private String zbCustSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.zb_pd
     *
     * @mbggenerated
     */
    private String zbPd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsNew_item
     *
     * @mbggenerated
     */
    private String isnewItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsNew_sup
     *
     * @mbggenerated
     */
    private String isnewSup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsNew_cust
     *
     * @mbggenerated
     */
    private String isnewCust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.db_guid
     *
     * @mbggenerated
     */
    private String dbGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_db
     *
     * @mbggenerated
     */
    private String branchDb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.parent_branch
     *
     * @mbggenerated
     */
    private String parentBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.create_man
     *
     * @mbggenerated
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.modify_man
     *
     * @mbggenerated
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.dist_discount
     *
     * @mbggenerated
     */
    private BigDecimal distDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.sale_price_type
     *
     * @mbggenerated
     */
    private String salePriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.vip_price_type
     *
     * @mbggenerated
     */
    private String vipPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.pf_price_type
     *
     * @mbggenerated
     */
    private String pfPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.branch_manage
     *
     * @mbggenerated
     */
    private String branchManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsEdit_item
     *
     * @mbggenerated
     */
    private String iseditItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsShare_stamp
     *
     * @mbggenerated
     */
    private String isshareStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.Is_OtherStock
     *
     * @mbggenerated
     */
    private String isOtherstock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsEdit_vip
     *
     * @mbggenerated
     */
    private String iseditVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.visa_no
     *
     * @mbggenerated
     */
    private String visaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.IsSee_in_price
     *
     * @mbggenerated
     */
    private String isseeInPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.db_price_type
     *
     * @mbggenerated
     */
    private String dbPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.db_price_mode
     *
     * @mbggenerated
     */
    private String dbPriceMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.server_reg
     *
     * @mbggenerated
     */
    private String serverReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.is_deal_cash
     *
     * @mbggenerated
     */
    private String isDealCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.vip_share_type
     *
     * @mbggenerated
     */
    private String vipShareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.store_mode
     *
     * @mbggenerated
     */
    private String storeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.store_sheng
     *
     * @mbggenerated
     */
    private String storeSheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.store_shi
     *
     * @mbggenerated
     */
    private String storeShi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.store_xian
     *
     * @mbggenerated
     */
    private String storeXian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.store_grant_no
     *
     * @mbggenerated
     */
    private String storeGrantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.py_code
     *
     * @mbggenerated
     */
    private String pyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.pd_allow
     *
     * @mbggenerated
     */
    private String pdAllow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.trans_vip_flow
     *
     * @mbggenerated
     */
    private String transVipFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.vip_class_edit
     *
     * @mbggenerated
     */
    private String vipClassEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch_info.ps_sq_app
     *
     * @mbggenerated
     */
    private String psSqApp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_no
     *
     * @return the value of t_branch_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_no
     *
     * @param branchNo the value for t_branch_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_name
     *
     * @return the value of t_branch_info.branch_name
     *
     * @mbggenerated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_name
     *
     * @param branchName the value for t_branch_info.branch_name
     *
     * @mbggenerated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_man
     *
     * @return the value of t_branch_info.branch_man
     *
     * @mbggenerated
     */
    public String getBranchMan() {
        return branchMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_man
     *
     * @param branchMan the value for t_branch_info.branch_man
     *
     * @mbggenerated
     */
    public void setBranchMan(String branchMan) {
        this.branchMan = branchMan == null ? null : branchMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_address
     *
     * @return the value of t_branch_info.branch_address
     *
     * @mbggenerated
     */
    public String getBranchAddress() {
        return branchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_address
     *
     * @param branchAddress the value for t_branch_info.branch_address
     *
     * @mbggenerated
     */
    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress == null ? null : branchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_zip
     *
     * @return the value of t_branch_info.branch_zip
     *
     * @mbggenerated
     */
    public String getBranchZip() {
        return branchZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_zip
     *
     * @param branchZip the value for t_branch_info.branch_zip
     *
     * @mbggenerated
     */
    public void setBranchZip(String branchZip) {
        this.branchZip = branchZip == null ? null : branchZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_email
     *
     * @return the value of t_branch_info.branch_email
     *
     * @mbggenerated
     */
    public String getBranchEmail() {
        return branchEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_email
     *
     * @param branchEmail the value for t_branch_info.branch_email
     *
     * @mbggenerated
     */
    public void setBranchEmail(String branchEmail) {
        this.branchEmail = branchEmail == null ? null : branchEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_tel
     *
     * @return the value of t_branch_info.branch_tel
     *
     * @mbggenerated
     */
    public String getBranchTel() {
        return branchTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_tel
     *
     * @param branchTel the value for t_branch_info.branch_tel
     *
     * @mbggenerated
     */
    public void setBranchTel(String branchTel) {
        this.branchTel = branchTel == null ? null : branchTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_fax
     *
     * @return the value of t_branch_info.branch_fax
     *
     * @mbggenerated
     */
    public String getBranchFax() {
        return branchFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_fax
     *
     * @param branchFax the value for t_branch_info.branch_fax
     *
     * @mbggenerated
     */
    public void setBranchFax(String branchFax) {
        this.branchFax = branchFax == null ? null : branchFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_memo
     *
     * @return the value of t_branch_info.branch_memo
     *
     * @mbggenerated
     */
    public String getBranchMemo() {
        return branchMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_memo
     *
     * @param branchMemo the value for t_branch_info.branch_memo
     *
     * @mbggenerated
     */
    public void setBranchMemo(String branchMemo) {
        this.branchMemo = branchMemo == null ? null : branchMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsSysFlag
     *
     * @return the value of t_branch_info.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsSysFlag
     *
     * @param issysflag the value for t_branch_info.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.update_flow
     *
     * @return the value of t_branch_info.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.update_flow
     *
     * @param updateFlow the value for t_branch_info.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.Store_type
     *
     * @return the value of t_branch_info.Store_type
     *
     * @mbggenerated
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.Store_type
     *
     * @param storeType the value for t_branch_info.Store_type
     *
     * @mbggenerated
     */
    public void setStoreType(String storeType) {
        this.storeType = storeType == null ? null : storeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.is_init
     *
     * @return the value of t_branch_info.is_init
     *
     * @mbggenerated
     */
    public String getIsInit() {
        return isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.is_init
     *
     * @param isInit the value for t_branch_info.is_init
     *
     * @mbggenerated
     */
    public void setIsInit(String isInit) {
        this.isInit = isInit == null ? null : isInit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.init_date
     *
     * @return the value of t_branch_info.init_date
     *
     * @mbggenerated
     */
    public Date getInitDate() {
        return initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.init_date
     *
     * @param initDate the value for t_branch_info.init_date
     *
     * @mbggenerated
     */
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.is_logout
     *
     * @return the value of t_branch_info.is_logout
     *
     * @mbggenerated
     */
    public String getIsLogout() {
        return isLogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.is_logout
     *
     * @param isLogout the value for t_branch_info.is_logout
     *
     * @mbggenerated
     */
    public void setIsLogout(String isLogout) {
        this.isLogout = isLogout == null ? null : isLogout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.logout_date
     *
     * @return the value of t_branch_info.logout_date
     *
     * @mbggenerated
     */
    public Date getLogoutDate() {
        return logoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.logout_date
     *
     * @param logoutDate the value for t_branch_info.logout_date
     *
     * @mbggenerated
     */
    public void setLogoutDate(Date logoutDate) {
        this.logoutDate = logoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_IsConnect
     *
     * @return the value of t_branch_info.server_IsConnect
     *
     * @mbggenerated
     */
    public String getServerIsconnect() {
        return serverIsconnect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_IsConnect
     *
     * @param serverIsconnect the value for t_branch_info.server_IsConnect
     *
     * @mbggenerated
     */
    public void setServerIsconnect(String serverIsconnect) {
        this.serverIsconnect = serverIsconnect == null ? null : serverIsconnect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_domain
     *
     * @return the value of t_branch_info.server_domain
     *
     * @mbggenerated
     */
    public String getServerDomain() {
        return serverDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_domain
     *
     * @param serverDomain the value for t_branch_info.server_domain
     *
     * @mbggenerated
     */
    public void setServerDomain(String serverDomain) {
        this.serverDomain = serverDomain == null ? null : serverDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_port
     *
     * @return the value of t_branch_info.server_port
     *
     * @mbggenerated
     */
    public Integer getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_port
     *
     * @param serverPort the value for t_branch_info.server_port
     *
     * @mbggenerated
     */
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_pwd
     *
     * @return the value of t_branch_info.server_pwd
     *
     * @mbggenerated
     */
    public String getServerPwd() {
        return serverPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_pwd
     *
     * @param serverPwd the value for t_branch_info.server_pwd
     *
     * @mbggenerated
     */
    public void setServerPwd(String serverPwd) {
        this.serverPwd = serverPwd == null ? null : serverPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_save
     *
     * @return the value of t_branch_info.IsShare_save
     *
     * @mbggenerated
     */
    public String getIsshareSave() {
        return isshareSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_save
     *
     * @param isshareSave the value for t_branch_info.IsShare_save
     *
     * @mbggenerated
     */
    public void setIsshareSave(String isshareSave) {
        this.isshareSave = isshareSave == null ? null : isshareSave.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_integral
     *
     * @return the value of t_branch_info.IsShare_integral
     *
     * @mbggenerated
     */
    public String getIsshareIntegral() {
        return isshareIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_integral
     *
     * @param isshareIntegral the value for t_branch_info.IsShare_integral
     *
     * @mbggenerated
     */
    public void setIsshareIntegral(String isshareIntegral) {
        this.isshareIntegral = isshareIntegral == null ? null : isshareIntegral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_ret
     *
     * @return the value of t_branch_info.IsShare_ret
     *
     * @mbggenerated
     */
    public String getIsshareRet() {
        return isshareRet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_ret
     *
     * @param isshareRet the value for t_branch_info.IsShare_ret
     *
     * @mbggenerated
     */
    public void setIsshareRet(String isshareRet) {
        this.isshareRet = isshareRet == null ? null : isshareRet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_give
     *
     * @return the value of t_branch_info.IsShare_give
     *
     * @mbggenerated
     */
    public String getIsshareGive() {
        return isshareGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_give
     *
     * @param isshareGive the value for t_branch_info.IsShare_give
     *
     * @mbggenerated
     */
    public void setIsshareGive(String isshareGive) {
        this.isshareGive = isshareGive == null ? null : isshareGive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_zero
     *
     * @return the value of t_branch_info.IsShare_zero
     *
     * @mbggenerated
     */
    public String getIsshareZero() {
        return isshareZero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_zero
     *
     * @param isshareZero the value for t_branch_info.IsShare_zero
     *
     * @mbggenerated
     */
    public void setIsshareZero(String isshareZero) {
        this.isshareZero = isshareZero == null ? null : isshareZero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_class
     *
     * @return the value of t_branch_info.branch_class
     *
     * @mbggenerated
     */
    public String getBranchClass() {
        return branchClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_class
     *
     * @param branchClass the value for t_branch_info.branch_class
     *
     * @mbggenerated
     */
    public void setBranchClass(String branchClass) {
        this.branchClass = branchClass == null ? null : branchClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.price_type
     *
     * @return the value of t_branch_info.price_type
     *
     * @mbggenerated
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.price_type
     *
     * @param priceType the value for t_branch_info.price_type
     *
     * @mbggenerated
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_limit
     *
     * @return the value of t_branch_info.IsShare_limit
     *
     * @mbggenerated
     */
    public String getIsshareLimit() {
        return isshareLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_limit
     *
     * @param isshareLimit the value for t_branch_info.IsShare_limit
     *
     * @mbggenerated
     */
    public void setIsshareLimit(String isshareLimit) {
        this.isshareLimit = isshareLimit == null ? null : isshareLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_pwd
     *
     * @return the value of t_branch_info.branch_pwd
     *
     * @mbggenerated
     */
    public String getBranchPwd() {
        return branchPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_pwd
     *
     * @param branchPwd the value for t_branch_info.branch_pwd
     *
     * @mbggenerated
     */
    public void setBranchPwd(String branchPwd) {
        this.branchPwd = branchPwd == null ? null : branchPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_user
     *
     * @return the value of t_branch_info.server_user
     *
     * @mbggenerated
     */
    public String getServerUser() {
        return serverUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_user
     *
     * @param serverUser the value for t_branch_info.server_user
     *
     * @mbggenerated
     */
    public void setServerUser(String serverUser) {
        this.serverUser = serverUser == null ? null : serverUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.price_mode
     *
     * @return the value of t_branch_info.price_mode
     *
     * @mbggenerated
     */
    public String getPriceMode() {
        return priceMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.price_mode
     *
     * @param priceMode the value for t_branch_info.price_mode
     *
     * @mbggenerated
     */
    public void setPriceMode(String priceMode) {
        this.priceMode = priceMode == null ? null : priceMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.zb_sup_settle
     *
     * @return the value of t_branch_info.zb_sup_settle
     *
     * @mbggenerated
     */
    public String getZbSupSettle() {
        return zbSupSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.zb_sup_settle
     *
     * @param zbSupSettle the value for t_branch_info.zb_sup_settle
     *
     * @mbggenerated
     */
    public void setZbSupSettle(String zbSupSettle) {
        this.zbSupSettle = zbSupSettle == null ? null : zbSupSettle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.zb_cust_settle
     *
     * @return the value of t_branch_info.zb_cust_settle
     *
     * @mbggenerated
     */
    public String getZbCustSettle() {
        return zbCustSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.zb_cust_settle
     *
     * @param zbCustSettle the value for t_branch_info.zb_cust_settle
     *
     * @mbggenerated
     */
    public void setZbCustSettle(String zbCustSettle) {
        this.zbCustSettle = zbCustSettle == null ? null : zbCustSettle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.zb_pd
     *
     * @return the value of t_branch_info.zb_pd
     *
     * @mbggenerated
     */
    public String getZbPd() {
        return zbPd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.zb_pd
     *
     * @param zbPd the value for t_branch_info.zb_pd
     *
     * @mbggenerated
     */
    public void setZbPd(String zbPd) {
        this.zbPd = zbPd == null ? null : zbPd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsNew_item
     *
     * @return the value of t_branch_info.IsNew_item
     *
     * @mbggenerated
     */
    public String getIsnewItem() {
        return isnewItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsNew_item
     *
     * @param isnewItem the value for t_branch_info.IsNew_item
     *
     * @mbggenerated
     */
    public void setIsnewItem(String isnewItem) {
        this.isnewItem = isnewItem == null ? null : isnewItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsNew_sup
     *
     * @return the value of t_branch_info.IsNew_sup
     *
     * @mbggenerated
     */
    public String getIsnewSup() {
        return isnewSup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsNew_sup
     *
     * @param isnewSup the value for t_branch_info.IsNew_sup
     *
     * @mbggenerated
     */
    public void setIsnewSup(String isnewSup) {
        this.isnewSup = isnewSup == null ? null : isnewSup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsNew_cust
     *
     * @return the value of t_branch_info.IsNew_cust
     *
     * @mbggenerated
     */
    public String getIsnewCust() {
        return isnewCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsNew_cust
     *
     * @param isnewCust the value for t_branch_info.IsNew_cust
     *
     * @mbggenerated
     */
    public void setIsnewCust(String isnewCust) {
        this.isnewCust = isnewCust == null ? null : isnewCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.db_guid
     *
     * @return the value of t_branch_info.db_guid
     *
     * @mbggenerated
     */
    public String getDbGuid() {
        return dbGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.db_guid
     *
     * @param dbGuid the value for t_branch_info.db_guid
     *
     * @mbggenerated
     */
    public void setDbGuid(String dbGuid) {
        this.dbGuid = dbGuid == null ? null : dbGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_db
     *
     * @return the value of t_branch_info.branch_db
     *
     * @mbggenerated
     */
    public String getBranchDb() {
        return branchDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_db
     *
     * @param branchDb the value for t_branch_info.branch_db
     *
     * @mbggenerated
     */
    public void setBranchDb(String branchDb) {
        this.branchDb = branchDb == null ? null : branchDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.parent_branch
     *
     * @return the value of t_branch_info.parent_branch
     *
     * @mbggenerated
     */
    public String getParentBranch() {
        return parentBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.parent_branch
     *
     * @param parentBranch the value for t_branch_info.parent_branch
     *
     * @mbggenerated
     */
    public void setParentBranch(String parentBranch) {
        this.parentBranch = parentBranch == null ? null : parentBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.update_time
     *
     * @return the value of t_branch_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.update_time
     *
     * @param updateTime the value for t_branch_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.update_branch
     *
     * @return the value of t_branch_info.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.update_branch
     *
     * @param updateBranch the value for t_branch_info.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.create_date
     *
     * @return the value of t_branch_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.create_date
     *
     * @param createDate the value for t_branch_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.create_man
     *
     * @return the value of t_branch_info.create_man
     *
     * @mbggenerated
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.create_man
     *
     * @param createMan the value for t_branch_info.create_man
     *
     * @mbggenerated
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.modify_date
     *
     * @return the value of t_branch_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.modify_date
     *
     * @param modifyDate the value for t_branch_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.modify_man
     *
     * @return the value of t_branch_info.modify_man
     *
     * @mbggenerated
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.modify_man
     *
     * @param modifyMan the value for t_branch_info.modify_man
     *
     * @mbggenerated
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.dist_discount
     *
     * @return the value of t_branch_info.dist_discount
     *
     * @mbggenerated
     */
    public BigDecimal getDistDiscount() {
        return distDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.dist_discount
     *
     * @param distDiscount the value for t_branch_info.dist_discount
     *
     * @mbggenerated
     */
    public void setDistDiscount(BigDecimal distDiscount) {
        this.distDiscount = distDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.sale_price_type
     *
     * @return the value of t_branch_info.sale_price_type
     *
     * @mbggenerated
     */
    public String getSalePriceType() {
        return salePriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.sale_price_type
     *
     * @param salePriceType the value for t_branch_info.sale_price_type
     *
     * @mbggenerated
     */
    public void setSalePriceType(String salePriceType) {
        this.salePriceType = salePriceType == null ? null : salePriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.vip_price_type
     *
     * @return the value of t_branch_info.vip_price_type
     *
     * @mbggenerated
     */
    public String getVipPriceType() {
        return vipPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.vip_price_type
     *
     * @param vipPriceType the value for t_branch_info.vip_price_type
     *
     * @mbggenerated
     */
    public void setVipPriceType(String vipPriceType) {
        this.vipPriceType = vipPriceType == null ? null : vipPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.pf_price_type
     *
     * @return the value of t_branch_info.pf_price_type
     *
     * @mbggenerated
     */
    public String getPfPriceType() {
        return pfPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.pf_price_type
     *
     * @param pfPriceType the value for t_branch_info.pf_price_type
     *
     * @mbggenerated
     */
    public void setPfPriceType(String pfPriceType) {
        this.pfPriceType = pfPriceType == null ? null : pfPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.branch_manage
     *
     * @return the value of t_branch_info.branch_manage
     *
     * @mbggenerated
     */
    public String getBranchManage() {
        return branchManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.branch_manage
     *
     * @param branchManage the value for t_branch_info.branch_manage
     *
     * @mbggenerated
     */
    public void setBranchManage(String branchManage) {
        this.branchManage = branchManage == null ? null : branchManage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsEdit_item
     *
     * @return the value of t_branch_info.IsEdit_item
     *
     * @mbggenerated
     */
    public String getIseditItem() {
        return iseditItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsEdit_item
     *
     * @param iseditItem the value for t_branch_info.IsEdit_item
     *
     * @mbggenerated
     */
    public void setIseditItem(String iseditItem) {
        this.iseditItem = iseditItem == null ? null : iseditItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsShare_stamp
     *
     * @return the value of t_branch_info.IsShare_stamp
     *
     * @mbggenerated
     */
    public String getIsshareStamp() {
        return isshareStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsShare_stamp
     *
     * @param isshareStamp the value for t_branch_info.IsShare_stamp
     *
     * @mbggenerated
     */
    public void setIsshareStamp(String isshareStamp) {
        this.isshareStamp = isshareStamp == null ? null : isshareStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.Is_OtherStock
     *
     * @return the value of t_branch_info.Is_OtherStock
     *
     * @mbggenerated
     */
    public String getIsOtherstock() {
        return isOtherstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.Is_OtherStock
     *
     * @param isOtherstock the value for t_branch_info.Is_OtherStock
     *
     * @mbggenerated
     */
    public void setIsOtherstock(String isOtherstock) {
        this.isOtherstock = isOtherstock == null ? null : isOtherstock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsEdit_vip
     *
     * @return the value of t_branch_info.IsEdit_vip
     *
     * @mbggenerated
     */
    public String getIseditVip() {
        return iseditVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsEdit_vip
     *
     * @param iseditVip the value for t_branch_info.IsEdit_vip
     *
     * @mbggenerated
     */
    public void setIseditVip(String iseditVip) {
        this.iseditVip = iseditVip == null ? null : iseditVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.visa_no
     *
     * @return the value of t_branch_info.visa_no
     *
     * @mbggenerated
     */
    public String getVisaNo() {
        return visaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.visa_no
     *
     * @param visaNo the value for t_branch_info.visa_no
     *
     * @mbggenerated
     */
    public void setVisaNo(String visaNo) {
        this.visaNo = visaNo == null ? null : visaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.IsSee_in_price
     *
     * @return the value of t_branch_info.IsSee_in_price
     *
     * @mbggenerated
     */
    public String getIsseeInPrice() {
        return isseeInPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.IsSee_in_price
     *
     * @param isseeInPrice the value for t_branch_info.IsSee_in_price
     *
     * @mbggenerated
     */
    public void setIsseeInPrice(String isseeInPrice) {
        this.isseeInPrice = isseeInPrice == null ? null : isseeInPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.db_price_type
     *
     * @return the value of t_branch_info.db_price_type
     *
     * @mbggenerated
     */
    public String getDbPriceType() {
        return dbPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.db_price_type
     *
     * @param dbPriceType the value for t_branch_info.db_price_type
     *
     * @mbggenerated
     */
    public void setDbPriceType(String dbPriceType) {
        this.dbPriceType = dbPriceType == null ? null : dbPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.db_price_mode
     *
     * @return the value of t_branch_info.db_price_mode
     *
     * @mbggenerated
     */
    public String getDbPriceMode() {
        return dbPriceMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.db_price_mode
     *
     * @param dbPriceMode the value for t_branch_info.db_price_mode
     *
     * @mbggenerated
     */
    public void setDbPriceMode(String dbPriceMode) {
        this.dbPriceMode = dbPriceMode == null ? null : dbPriceMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.server_reg
     *
     * @return the value of t_branch_info.server_reg
     *
     * @mbggenerated
     */
    public String getServerReg() {
        return serverReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.server_reg
     *
     * @param serverReg the value for t_branch_info.server_reg
     *
     * @mbggenerated
     */
    public void setServerReg(String serverReg) {
        this.serverReg = serverReg == null ? null : serverReg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.is_deal_cash
     *
     * @return the value of t_branch_info.is_deal_cash
     *
     * @mbggenerated
     */
    public String getIsDealCash() {
        return isDealCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.is_deal_cash
     *
     * @param isDealCash the value for t_branch_info.is_deal_cash
     *
     * @mbggenerated
     */
    public void setIsDealCash(String isDealCash) {
        this.isDealCash = isDealCash == null ? null : isDealCash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.vip_share_type
     *
     * @return the value of t_branch_info.vip_share_type
     *
     * @mbggenerated
     */
    public String getVipShareType() {
        return vipShareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.vip_share_type
     *
     * @param vipShareType the value for t_branch_info.vip_share_type
     *
     * @mbggenerated
     */
    public void setVipShareType(String vipShareType) {
        this.vipShareType = vipShareType == null ? null : vipShareType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.store_mode
     *
     * @return the value of t_branch_info.store_mode
     *
     * @mbggenerated
     */
    public String getStoreMode() {
        return storeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.store_mode
     *
     * @param storeMode the value for t_branch_info.store_mode
     *
     * @mbggenerated
     */
    public void setStoreMode(String storeMode) {
        this.storeMode = storeMode == null ? null : storeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.store_sheng
     *
     * @return the value of t_branch_info.store_sheng
     *
     * @mbggenerated
     */
    public String getStoreSheng() {
        return storeSheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.store_sheng
     *
     * @param storeSheng the value for t_branch_info.store_sheng
     *
     * @mbggenerated
     */
    public void setStoreSheng(String storeSheng) {
        this.storeSheng = storeSheng == null ? null : storeSheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.store_shi
     *
     * @return the value of t_branch_info.store_shi
     *
     * @mbggenerated
     */
    public String getStoreShi() {
        return storeShi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.store_shi
     *
     * @param storeShi the value for t_branch_info.store_shi
     *
     * @mbggenerated
     */
    public void setStoreShi(String storeShi) {
        this.storeShi = storeShi == null ? null : storeShi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.store_xian
     *
     * @return the value of t_branch_info.store_xian
     *
     * @mbggenerated
     */
    public String getStoreXian() {
        return storeXian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.store_xian
     *
     * @param storeXian the value for t_branch_info.store_xian
     *
     * @mbggenerated
     */
    public void setStoreXian(String storeXian) {
        this.storeXian = storeXian == null ? null : storeXian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.store_grant_no
     *
     * @return the value of t_branch_info.store_grant_no
     *
     * @mbggenerated
     */
    public String getStoreGrantNo() {
        return storeGrantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.store_grant_no
     *
     * @param storeGrantNo the value for t_branch_info.store_grant_no
     *
     * @mbggenerated
     */
    public void setStoreGrantNo(String storeGrantNo) {
        this.storeGrantNo = storeGrantNo == null ? null : storeGrantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.py_code
     *
     * @return the value of t_branch_info.py_code
     *
     * @mbggenerated
     */
    public String getPyCode() {
        return pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.py_code
     *
     * @param pyCode the value for t_branch_info.py_code
     *
     * @mbggenerated
     */
    public void setPyCode(String pyCode) {
        this.pyCode = pyCode == null ? null : pyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.pd_allow
     *
     * @return the value of t_branch_info.pd_allow
     *
     * @mbggenerated
     */
    public String getPdAllow() {
        return pdAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.pd_allow
     *
     * @param pdAllow the value for t_branch_info.pd_allow
     *
     * @mbggenerated
     */
    public void setPdAllow(String pdAllow) {
        this.pdAllow = pdAllow == null ? null : pdAllow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.trans_upflag
     *
     * @return the value of t_branch_info.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.trans_upflag
     *
     * @param transUpflag the value for t_branch_info.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.trans_vip_flow
     *
     * @return the value of t_branch_info.trans_vip_flow
     *
     * @mbggenerated
     */
    public String getTransVipFlow() {
        return transVipFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.trans_vip_flow
     *
     * @param transVipFlow the value for t_branch_info.trans_vip_flow
     *
     * @mbggenerated
     */
    public void setTransVipFlow(String transVipFlow) {
        this.transVipFlow = transVipFlow == null ? null : transVipFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.vip_class_edit
     *
     * @return the value of t_branch_info.vip_class_edit
     *
     * @mbggenerated
     */
    public String getVipClassEdit() {
        return vipClassEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.vip_class_edit
     *
     * @param vipClassEdit the value for t_branch_info.vip_class_edit
     *
     * @mbggenerated
     */
    public void setVipClassEdit(String vipClassEdit) {
        this.vipClassEdit = vipClassEdit == null ? null : vipClassEdit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch_info.ps_sq_app
     *
     * @return the value of t_branch_info.ps_sq_app
     *
     * @mbggenerated
     */
    public String getPsSqApp() {
        return psSqApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch_info.ps_sq_app
     *
     * @param psSqApp the value for t_branch_info.ps_sq_app
     *
     * @mbggenerated
     */
    public void setPsSqApp(String psSqApp) {
        this.psSqApp = psSqApp == null ? null : psSqApp.trim();
    }
}