package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TDataPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_no
     *
     * @mbggenerated
     */
    private String paymentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_name
     *
     * @mbggenerated
     */
    private String paymentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsPos
     *
     * @mbggenerated
     */
    private String paymentIspos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsHt
     *
     * @mbggenerated
     */
    private String paymentIsht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsZero
     *
     * @mbggenerated
     */
    private String paymentIszero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsMore
     *
     * @mbggenerated
     */
    private String paymentIsmore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsCash
     *
     * @mbggenerated
     */
    private String paymentIscash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.coin_no
     *
     * @mbggenerated
     */
    private String coinNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.visa_no
     *
     * @mbggenerated
     */
    private String visaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.pos_shortcut_sys
     *
     * @mbggenerated
     */
    private String posShortcutSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.pos_shortcut_User
     *
     * @mbggenerated
     */
    private String posShortcutUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_memo
     *
     * @mbggenerated
     */
    private String paymentMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsSn
     *
     * @mbggenerated
     */
    private String paymentIssn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsMemo
     *
     * @mbggenerated
     */
    private String paymentIsmemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsTax
     *
     * @mbggenerated
     */
    private String paymentIstax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.touch_index
     *
     * @mbggenerated
     */
    private Integer touchIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.charge_rate
     *
     * @mbggenerated
     */
    private BigDecimal chargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.charge_max_amt
     *
     * @mbggenerated
     */
    private BigDecimal chargeMaxAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.payment_IsReal
     *
     * @mbggenerated
     */
    private String paymentIsreal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_payment.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_no
     *
     * @return the value of t_data_payment.payment_no
     *
     * @mbggenerated
     */
    public String getPaymentNo() {
        return paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_no
     *
     * @param paymentNo the value for t_data_payment.payment_no
     *
     * @mbggenerated
     */
    public void setPaymentNo(String paymentNo) {
        this.paymentNo = paymentNo == null ? null : paymentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_name
     *
     * @return the value of t_data_payment.payment_name
     *
     * @mbggenerated
     */
    public String getPaymentName() {
        return paymentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_name
     *
     * @param paymentName the value for t_data_payment.payment_name
     *
     * @mbggenerated
     */
    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName == null ? null : paymentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsPos
     *
     * @return the value of t_data_payment.payment_IsPos
     *
     * @mbggenerated
     */
    public String getPaymentIspos() {
        return paymentIspos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsPos
     *
     * @param paymentIspos the value for t_data_payment.payment_IsPos
     *
     * @mbggenerated
     */
    public void setPaymentIspos(String paymentIspos) {
        this.paymentIspos = paymentIspos == null ? null : paymentIspos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsHt
     *
     * @return the value of t_data_payment.payment_IsHt
     *
     * @mbggenerated
     */
    public String getPaymentIsht() {
        return paymentIsht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsHt
     *
     * @param paymentIsht the value for t_data_payment.payment_IsHt
     *
     * @mbggenerated
     */
    public void setPaymentIsht(String paymentIsht) {
        this.paymentIsht = paymentIsht == null ? null : paymentIsht.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsZero
     *
     * @return the value of t_data_payment.payment_IsZero
     *
     * @mbggenerated
     */
    public String getPaymentIszero() {
        return paymentIszero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsZero
     *
     * @param paymentIszero the value for t_data_payment.payment_IsZero
     *
     * @mbggenerated
     */
    public void setPaymentIszero(String paymentIszero) {
        this.paymentIszero = paymentIszero == null ? null : paymentIszero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsMore
     *
     * @return the value of t_data_payment.payment_IsMore
     *
     * @mbggenerated
     */
    public String getPaymentIsmore() {
        return paymentIsmore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsMore
     *
     * @param paymentIsmore the value for t_data_payment.payment_IsMore
     *
     * @mbggenerated
     */
    public void setPaymentIsmore(String paymentIsmore) {
        this.paymentIsmore = paymentIsmore == null ? null : paymentIsmore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsCash
     *
     * @return the value of t_data_payment.payment_IsCash
     *
     * @mbggenerated
     */
    public String getPaymentIscash() {
        return paymentIscash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsCash
     *
     * @param paymentIscash the value for t_data_payment.payment_IsCash
     *
     * @mbggenerated
     */
    public void setPaymentIscash(String paymentIscash) {
        this.paymentIscash = paymentIscash == null ? null : paymentIscash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.coin_no
     *
     * @return the value of t_data_payment.coin_no
     *
     * @mbggenerated
     */
    public String getCoinNo() {
        return coinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.coin_no
     *
     * @param coinNo the value for t_data_payment.coin_no
     *
     * @mbggenerated
     */
    public void setCoinNo(String coinNo) {
        this.coinNo = coinNo == null ? null : coinNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.visa_no
     *
     * @return the value of t_data_payment.visa_no
     *
     * @mbggenerated
     */
    public String getVisaNo() {
        return visaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.visa_no
     *
     * @param visaNo the value for t_data_payment.visa_no
     *
     * @mbggenerated
     */
    public void setVisaNo(String visaNo) {
        this.visaNo = visaNo == null ? null : visaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.pos_shortcut_sys
     *
     * @return the value of t_data_payment.pos_shortcut_sys
     *
     * @mbggenerated
     */
    public String getPosShortcutSys() {
        return posShortcutSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.pos_shortcut_sys
     *
     * @param posShortcutSys the value for t_data_payment.pos_shortcut_sys
     *
     * @mbggenerated
     */
    public void setPosShortcutSys(String posShortcutSys) {
        this.posShortcutSys = posShortcutSys == null ? null : posShortcutSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.pos_shortcut_User
     *
     * @return the value of t_data_payment.pos_shortcut_User
     *
     * @mbggenerated
     */
    public String getPosShortcutUser() {
        return posShortcutUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.pos_shortcut_User
     *
     * @param posShortcutUser the value for t_data_payment.pos_shortcut_User
     *
     * @mbggenerated
     */
    public void setPosShortcutUser(String posShortcutUser) {
        this.posShortcutUser = posShortcutUser == null ? null : posShortcutUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_memo
     *
     * @return the value of t_data_payment.payment_memo
     *
     * @mbggenerated
     */
    public String getPaymentMemo() {
        return paymentMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_memo
     *
     * @param paymentMemo the value for t_data_payment.payment_memo
     *
     * @mbggenerated
     */
    public void setPaymentMemo(String paymentMemo) {
        this.paymentMemo = paymentMemo == null ? null : paymentMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.IsSysFlag
     *
     * @return the value of t_data_payment.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.IsSysFlag
     *
     * @param issysflag the value for t_data_payment.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.create_user
     *
     * @return the value of t_data_payment.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.create_user
     *
     * @param createUser the value for t_data_payment.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.create_date
     *
     * @return the value of t_data_payment.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.create_date
     *
     * @param createDate the value for t_data_payment.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.modify_user
     *
     * @return the value of t_data_payment.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.modify_user
     *
     * @param modifyUser the value for t_data_payment.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.modify_date
     *
     * @return the value of t_data_payment.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.modify_date
     *
     * @param modifyDate the value for t_data_payment.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.update_flow
     *
     * @return the value of t_data_payment.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.update_flow
     *
     * @param updateFlow the value for t_data_payment.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsSn
     *
     * @return the value of t_data_payment.payment_IsSn
     *
     * @mbggenerated
     */
    public String getPaymentIssn() {
        return paymentIssn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsSn
     *
     * @param paymentIssn the value for t_data_payment.payment_IsSn
     *
     * @mbggenerated
     */
    public void setPaymentIssn(String paymentIssn) {
        this.paymentIssn = paymentIssn == null ? null : paymentIssn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsMemo
     *
     * @return the value of t_data_payment.payment_IsMemo
     *
     * @mbggenerated
     */
    public String getPaymentIsmemo() {
        return paymentIsmemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsMemo
     *
     * @param paymentIsmemo the value for t_data_payment.payment_IsMemo
     *
     * @mbggenerated
     */
    public void setPaymentIsmemo(String paymentIsmemo) {
        this.paymentIsmemo = paymentIsmemo == null ? null : paymentIsmemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsTax
     *
     * @return the value of t_data_payment.payment_IsTax
     *
     * @mbggenerated
     */
    public String getPaymentIstax() {
        return paymentIstax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsTax
     *
     * @param paymentIstax the value for t_data_payment.payment_IsTax
     *
     * @mbggenerated
     */
    public void setPaymentIstax(String paymentIstax) {
        this.paymentIstax = paymentIstax == null ? null : paymentIstax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.update_time
     *
     * @return the value of t_data_payment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.update_time
     *
     * @param updateTime the value for t_data_payment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.update_branch
     *
     * @return the value of t_data_payment.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.update_branch
     *
     * @param updateBranch the value for t_data_payment.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.touch_index
     *
     * @return the value of t_data_payment.touch_index
     *
     * @mbggenerated
     */
    public Integer getTouchIndex() {
        return touchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.touch_index
     *
     * @param touchIndex the value for t_data_payment.touch_index
     *
     * @mbggenerated
     */
    public void setTouchIndex(Integer touchIndex) {
        this.touchIndex = touchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.charge_rate
     *
     * @return the value of t_data_payment.charge_rate
     *
     * @mbggenerated
     */
    public BigDecimal getChargeRate() {
        return chargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.charge_rate
     *
     * @param chargeRate the value for t_data_payment.charge_rate
     *
     * @mbggenerated
     */
    public void setChargeRate(BigDecimal chargeRate) {
        this.chargeRate = chargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.charge_max_amt
     *
     * @return the value of t_data_payment.charge_max_amt
     *
     * @mbggenerated
     */
    public BigDecimal getChargeMaxAmt() {
        return chargeMaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.charge_max_amt
     *
     * @param chargeMaxAmt the value for t_data_payment.charge_max_amt
     *
     * @mbggenerated
     */
    public void setChargeMaxAmt(BigDecimal chargeMaxAmt) {
        this.chargeMaxAmt = chargeMaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.payment_IsReal
     *
     * @return the value of t_data_payment.payment_IsReal
     *
     * @mbggenerated
     */
    public String getPaymentIsreal() {
        return paymentIsreal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.payment_IsReal
     *
     * @param paymentIsreal the value for t_data_payment.payment_IsReal
     *
     * @mbggenerated
     */
    public void setPaymentIsreal(String paymentIsreal) {
        this.paymentIsreal = paymentIsreal == null ? null : paymentIsreal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_payment.trans_upflag
     *
     * @return the value of t_data_payment.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_payment.trans_upflag
     *
     * @param transUpflag the value for t_data_payment.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }
}