package com.gd.data.entity;

import java.util.Date;

public class TItemBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.item_brand
     *
     * @mbggenerated
     */
    private String itemBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_memo
     *
     * @mbggenerated
     */
    private String brandMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.brand_py
     *
     * @mbggenerated
     */
    private String brandPy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_brand.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.item_brand
     *
     * @return the value of t_item_brand.item_brand
     *
     * @mbggenerated
     */
    public String getItemBrand() {
        return itemBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.item_brand
     *
     * @param itemBrand the value for t_item_brand.item_brand
     *
     * @mbggenerated
     */
    public void setItemBrand(String itemBrand) {
        this.itemBrand = itemBrand == null ? null : itemBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_name
     *
     * @return the value of t_item_brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_name
     *
     * @param brandName the value for t_item_brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_memo
     *
     * @return the value of t_item_brand.brand_memo
     *
     * @mbggenerated
     */
    public String getBrandMemo() {
        return brandMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_memo
     *
     * @param brandMemo the value for t_item_brand.brand_memo
     *
     * @mbggenerated
     */
    public void setBrandMemo(String brandMemo) {
        this.brandMemo = brandMemo == null ? null : brandMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.IsSysFlag
     *
     * @return the value of t_item_brand.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.IsSysFlag
     *
     * @param issysflag the value for t_item_brand.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.update_flow
     *
     * @return the value of t_item_brand.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.update_flow
     *
     * @param updateFlow the value for t_item_brand.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.update_time
     *
     * @return the value of t_item_brand.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.update_time
     *
     * @param updateTime the value for t_item_brand.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.update_branch
     *
     * @return the value of t_item_brand.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.update_branch
     *
     * @param updateBranch the value for t_item_brand.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.brand_py
     *
     * @return the value of t_item_brand.brand_py
     *
     * @mbggenerated
     */
    public String getBrandPy() {
        return brandPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.brand_py
     *
     * @param brandPy the value for t_item_brand.brand_py
     *
     * @mbggenerated
     */
    public void setBrandPy(String brandPy) {
        this.brandPy = brandPy == null ? null : brandPy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_brand.trans_upflag
     *
     * @return the value of t_item_brand.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_brand.trans_upflag
     *
     * @param transUpflag the value for t_item_brand.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }
}