package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TItemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_subno
     *
     * @mbggenerated
     */
    private String itemSubno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_barcode
     *
     * @mbggenerated
     */
    private String itemBarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_class
     *
     * @mbggenerated
     */
    private String itemClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_property
     *
     * @mbggenerated
     */
    private String itemProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_brand
     *
     * @mbggenerated
     */
    private String itemBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_size
     *
     * @mbggenerated
     */
    private String itemSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_unit_no
     *
     * @mbggenerated
     */
    private String itemUnitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_in_price
     *
     * @mbggenerated
     */
    private BigDecimal itemInPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_sale_price
     *
     * @mbggenerated
     */
    private BigDecimal itemSalePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_pf_price
     *
     * @mbggenerated
     */
    private BigDecimal itemPfPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_vip_price
     *
     * @mbggenerated
     */
    private BigDecimal itemVipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_dist_price
     *
     * @mbggenerated
     */
    private BigDecimal itemDistPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_area
     *
     * @mbggenerated
     */
    private String itemArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_grade
     *
     * @mbggenerated
     */
    private String itemGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_sup_no
     *
     * @mbggenerated
     */
    private String itemSupNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.counter_no
     *
     * @mbggenerated
     */
    private String counterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_combine
     *
     * @mbggenerated
     */
    private String itemCombine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_SaleMode
     *
     * @mbggenerated
     */
    private String itemSalemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_flag
     *
     * @mbggenerated
     */
    private String itemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.have_stock
     *
     * @mbggenerated
     */
    private String haveStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.Manage_type
     *
     * @mbggenerated
     */
    private String manageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    private BigDecimal manageLyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.py_code
     *
     * @mbggenerated
     */
    private String pyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_valid_day
     *
     * @mbggenerated
     */
    private BigDecimal itemValidDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_valid_tipday
     *
     * @mbggenerated
     */
    private BigDecimal itemValidTipday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.pos_lower_price
     *
     * @mbggenerated
     */
    private BigDecimal posLowerPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.pos_discount
     *
     * @mbggenerated
     */
    private BigDecimal posDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.change_price
     *
     * @mbggenerated
     */
    private String changePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.allow_discount
     *
     * @mbggenerated
     */
    private String allowDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.in_tax_rate
     *
     * @mbggenerated
     */
    private BigDecimal inTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.out_tax_rate
     *
     * @mbggenerated
     */
    private BigDecimal outTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_sale_rate
     *
     * @mbggenerated
     */
    private BigDecimal itemSaleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_pf_rate
     *
     * @mbggenerated
     */
    private BigDecimal itemPfRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.integral_rate
     *
     * @mbggenerated
     */
    private BigDecimal integralRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.cost_type
     *
     * @mbggenerated
     */
    private String costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.internal_flag
     *
     * @mbggenerated
     */
    private String internalFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_memo
     *
     * @mbggenerated
     */
    private String itemMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bytxt1
     *
     * @mbggenerated
     */
    private String itemBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bytxt2
     *
     * @mbggenerated
     */
    private String itemBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bytxt3
     *
     * @mbggenerated
     */
    private String itemBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bynum1
     *
     * @mbggenerated
     */
    private BigDecimal itemBynum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bynum2
     *
     * @mbggenerated
     */
    private BigDecimal itemBynum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_bynum3
     *
     * @mbggenerated
     */
    private BigDecimal itemBynum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.lock_user
     *
     * @mbggenerated
     */
    private String lockUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_sale_ratetype
     *
     * @mbggenerated
     */
    private String itemSaleRatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_pf_ratetype
     *
     * @mbggenerated
     */
    private String itemPfRatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_date_unit
     *
     * @mbggenerated
     */
    private String itemDateUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.showbox_no
     *
     * @mbggenerated
     */
    private String showboxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_in_ratetype
     *
     * @mbggenerated
     */
    private String itemInRatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_in_rate
     *
     * @mbggenerated
     */
    private BigDecimal itemInRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_IsGood
     *
     * @mbggenerated
     */
    private String itemIsgood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_abc
     *
     * @mbggenerated
     */
    private String itemAbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_print_label
     *
     * @mbggenerated
     */
    private String itemPrintLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_qa_cert
     *
     * @mbggenerated
     */
    private String itemQaCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_qs_cert
     *
     * @mbggenerated
     */
    private String itemQsCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_inlet_cert
     *
     * @mbggenerated
     */
    private String itemInletCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_qi_rep
     *
     * @mbggenerated
     */
    private String itemQiRep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.have_saleman
     *
     * @mbggenerated
     */
    private String haveSaleman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_dist_qty
     *
     * @mbggenerated
     */
    private BigDecimal itemDistQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_dist_limit
     *
     * @mbggenerated
     */
    private String itemDistLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_dist_double
     *
     * @mbggenerated
     */
    private String itemDistDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_pzwh
     *
     * @mbggenerated
     */
    private String itemPzwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_factory
     *
     * @mbggenerated
     */
    private String itemFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_sys_memo1
     *
     * @mbggenerated
     */
    private String itemSysMemo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.have_salememo
     *
     * @mbggenerated
     */
    private String haveSalememo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.buy_days
     *
     * @mbggenerated
     */
    private Integer buyDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.pos_limit_qty
     *
     * @mbggenerated
     */
    private BigDecimal posLimitQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_yp_flag
     *
     * @mbggenerated
     */
    private String itemYpFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.eshop_Integral
     *
     * @mbggenerated
     */
    private BigDecimal eshopIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_jj
     *
     * @mbggenerated
     */
    private String itemJj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_info.item_ks
     *
     * @mbggenerated
     */
    private String itemKs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_no
     *
     * @return the value of t_item_info.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_no
     *
     * @param itemNo the value for t_item_info.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_subno
     *
     * @return the value of t_item_info.item_subno
     *
     * @mbggenerated
     */
    public String getItemSubno() {
        return itemSubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_subno
     *
     * @param itemSubno the value for t_item_info.item_subno
     *
     * @mbggenerated
     */
    public void setItemSubno(String itemSubno) {
        this.itemSubno = itemSubno == null ? null : itemSubno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_barcode
     *
     * @return the value of t_item_info.item_barcode
     *
     * @mbggenerated
     */
    public String getItemBarcode() {
        return itemBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_barcode
     *
     * @param itemBarcode the value for t_item_info.item_barcode
     *
     * @mbggenerated
     */
    public void setItemBarcode(String itemBarcode) {
        this.itemBarcode = itemBarcode == null ? null : itemBarcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_name
     *
     * @return the value of t_item_info.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_name
     *
     * @param itemName the value for t_item_info.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_class
     *
     * @return the value of t_item_info.item_class
     *
     * @mbggenerated
     */
    public String getItemClass() {
        return itemClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_class
     *
     * @param itemClass the value for t_item_info.item_class
     *
     * @mbggenerated
     */
    public void setItemClass(String itemClass) {
        this.itemClass = itemClass == null ? null : itemClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_property
     *
     * @return the value of t_item_info.item_property
     *
     * @mbggenerated
     */
    public String getItemProperty() {
        return itemProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_property
     *
     * @param itemProperty the value for t_item_info.item_property
     *
     * @mbggenerated
     */
    public void setItemProperty(String itemProperty) {
        this.itemProperty = itemProperty == null ? null : itemProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_brand
     *
     * @return the value of t_item_info.item_brand
     *
     * @mbggenerated
     */
    public String getItemBrand() {
        return itemBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_brand
     *
     * @param itemBrand the value for t_item_info.item_brand
     *
     * @mbggenerated
     */
    public void setItemBrand(String itemBrand) {
        this.itemBrand = itemBrand == null ? null : itemBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_size
     *
     * @return the value of t_item_info.item_size
     *
     * @mbggenerated
     */
    public String getItemSize() {
        return itemSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_size
     *
     * @param itemSize the value for t_item_info.item_size
     *
     * @mbggenerated
     */
    public void setItemSize(String itemSize) {
        this.itemSize = itemSize == null ? null : itemSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_unit_no
     *
     * @return the value of t_item_info.item_unit_no
     *
     * @mbggenerated
     */
    public String getItemUnitNo() {
        return itemUnitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_unit_no
     *
     * @param itemUnitNo the value for t_item_info.item_unit_no
     *
     * @mbggenerated
     */
    public void setItemUnitNo(String itemUnitNo) {
        this.itemUnitNo = itemUnitNo == null ? null : itemUnitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_in_price
     *
     * @return the value of t_item_info.item_in_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemInPrice() {
        return itemInPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_in_price
     *
     * @param itemInPrice the value for t_item_info.item_in_price
     *
     * @mbggenerated
     */
    public void setItemInPrice(BigDecimal itemInPrice) {
        this.itemInPrice = itemInPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_sale_price
     *
     * @return the value of t_item_info.item_sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemSalePrice() {
        return itemSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_sale_price
     *
     * @param itemSalePrice the value for t_item_info.item_sale_price
     *
     * @mbggenerated
     */
    public void setItemSalePrice(BigDecimal itemSalePrice) {
        this.itemSalePrice = itemSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_pf_price
     *
     * @return the value of t_item_info.item_pf_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemPfPrice() {
        return itemPfPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_pf_price
     *
     * @param itemPfPrice the value for t_item_info.item_pf_price
     *
     * @mbggenerated
     */
    public void setItemPfPrice(BigDecimal itemPfPrice) {
        this.itemPfPrice = itemPfPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_vip_price
     *
     * @return the value of t_item_info.item_vip_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemVipPrice() {
        return itemVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_vip_price
     *
     * @param itemVipPrice the value for t_item_info.item_vip_price
     *
     * @mbggenerated
     */
    public void setItemVipPrice(BigDecimal itemVipPrice) {
        this.itemVipPrice = itemVipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_dist_price
     *
     * @return the value of t_item_info.item_dist_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemDistPrice() {
        return itemDistPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_dist_price
     *
     * @param itemDistPrice the value for t_item_info.item_dist_price
     *
     * @mbggenerated
     */
    public void setItemDistPrice(BigDecimal itemDistPrice) {
        this.itemDistPrice = itemDistPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_area
     *
     * @return the value of t_item_info.item_area
     *
     * @mbggenerated
     */
    public String getItemArea() {
        return itemArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_area
     *
     * @param itemArea the value for t_item_info.item_area
     *
     * @mbggenerated
     */
    public void setItemArea(String itemArea) {
        this.itemArea = itemArea == null ? null : itemArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_grade
     *
     * @return the value of t_item_info.item_grade
     *
     * @mbggenerated
     */
    public String getItemGrade() {
        return itemGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_grade
     *
     * @param itemGrade the value for t_item_info.item_grade
     *
     * @mbggenerated
     */
    public void setItemGrade(String itemGrade) {
        this.itemGrade = itemGrade == null ? null : itemGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_sup_no
     *
     * @return the value of t_item_info.item_sup_no
     *
     * @mbggenerated
     */
    public String getItemSupNo() {
        return itemSupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_sup_no
     *
     * @param itemSupNo the value for t_item_info.item_sup_no
     *
     * @mbggenerated
     */
    public void setItemSupNo(String itemSupNo) {
        this.itemSupNo = itemSupNo == null ? null : itemSupNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.counter_no
     *
     * @return the value of t_item_info.counter_no
     *
     * @mbggenerated
     */
    public String getCounterNo() {
        return counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.counter_no
     *
     * @param counterNo the value for t_item_info.counter_no
     *
     * @mbggenerated
     */
    public void setCounterNo(String counterNo) {
        this.counterNo = counterNo == null ? null : counterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_combine
     *
     * @return the value of t_item_info.item_combine
     *
     * @mbggenerated
     */
    public String getItemCombine() {
        return itemCombine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_combine
     *
     * @param itemCombine the value for t_item_info.item_combine
     *
     * @mbggenerated
     */
    public void setItemCombine(String itemCombine) {
        this.itemCombine = itemCombine == null ? null : itemCombine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_SaleMode
     *
     * @return the value of t_item_info.item_SaleMode
     *
     * @mbggenerated
     */
    public String getItemSalemode() {
        return itemSalemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_SaleMode
     *
     * @param itemSalemode the value for t_item_info.item_SaleMode
     *
     * @mbggenerated
     */
    public void setItemSalemode(String itemSalemode) {
        this.itemSalemode = itemSalemode == null ? null : itemSalemode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_flag
     *
     * @return the value of t_item_info.item_flag
     *
     * @mbggenerated
     */
    public String getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_flag
     *
     * @param itemFlag the value for t_item_info.item_flag
     *
     * @mbggenerated
     */
    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag == null ? null : itemFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.have_stock
     *
     * @return the value of t_item_info.have_stock
     *
     * @mbggenerated
     */
    public String getHaveStock() {
        return haveStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.have_stock
     *
     * @param haveStock the value for t_item_info.have_stock
     *
     * @mbggenerated
     */
    public void setHaveStock(String haveStock) {
        this.haveStock = haveStock == null ? null : haveStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.Manage_type
     *
     * @return the value of t_item_info.Manage_type
     *
     * @mbggenerated
     */
    public String getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.Manage_type
     *
     * @param manageType the value for t_item_info.Manage_type
     *
     * @mbggenerated
     */
    public void setManageType(String manageType) {
        this.manageType = manageType == null ? null : manageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.Manage_ly_rate
     *
     * @return the value of t_item_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    public BigDecimal getManageLyRate() {
        return manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.Manage_ly_rate
     *
     * @param manageLyRate the value for t_item_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    public void setManageLyRate(BigDecimal manageLyRate) {
        this.manageLyRate = manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.py_code
     *
     * @return the value of t_item_info.py_code
     *
     * @mbggenerated
     */
    public String getPyCode() {
        return pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.py_code
     *
     * @param pyCode the value for t_item_info.py_code
     *
     * @mbggenerated
     */
    public void setPyCode(String pyCode) {
        this.pyCode = pyCode == null ? null : pyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_valid_day
     *
     * @return the value of t_item_info.item_valid_day
     *
     * @mbggenerated
     */
    public BigDecimal getItemValidDay() {
        return itemValidDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_valid_day
     *
     * @param itemValidDay the value for t_item_info.item_valid_day
     *
     * @mbggenerated
     */
    public void setItemValidDay(BigDecimal itemValidDay) {
        this.itemValidDay = itemValidDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_valid_tipday
     *
     * @return the value of t_item_info.item_valid_tipday
     *
     * @mbggenerated
     */
    public BigDecimal getItemValidTipday() {
        return itemValidTipday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_valid_tipday
     *
     * @param itemValidTipday the value for t_item_info.item_valid_tipday
     *
     * @mbggenerated
     */
    public void setItemValidTipday(BigDecimal itemValidTipday) {
        this.itemValidTipday = itemValidTipday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.pos_lower_price
     *
     * @return the value of t_item_info.pos_lower_price
     *
     * @mbggenerated
     */
    public BigDecimal getPosLowerPrice() {
        return posLowerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.pos_lower_price
     *
     * @param posLowerPrice the value for t_item_info.pos_lower_price
     *
     * @mbggenerated
     */
    public void setPosLowerPrice(BigDecimal posLowerPrice) {
        this.posLowerPrice = posLowerPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.pos_discount
     *
     * @return the value of t_item_info.pos_discount
     *
     * @mbggenerated
     */
    public BigDecimal getPosDiscount() {
        return posDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.pos_discount
     *
     * @param posDiscount the value for t_item_info.pos_discount
     *
     * @mbggenerated
     */
    public void setPosDiscount(BigDecimal posDiscount) {
        this.posDiscount = posDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.change_price
     *
     * @return the value of t_item_info.change_price
     *
     * @mbggenerated
     */
    public String getChangePrice() {
        return changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.change_price
     *
     * @param changePrice the value for t_item_info.change_price
     *
     * @mbggenerated
     */
    public void setChangePrice(String changePrice) {
        this.changePrice = changePrice == null ? null : changePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.allow_discount
     *
     * @return the value of t_item_info.allow_discount
     *
     * @mbggenerated
     */
    public String getAllowDiscount() {
        return allowDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.allow_discount
     *
     * @param allowDiscount the value for t_item_info.allow_discount
     *
     * @mbggenerated
     */
    public void setAllowDiscount(String allowDiscount) {
        this.allowDiscount = allowDiscount == null ? null : allowDiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.in_tax_rate
     *
     * @return the value of t_item_info.in_tax_rate
     *
     * @mbggenerated
     */
    public BigDecimal getInTaxRate() {
        return inTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.in_tax_rate
     *
     * @param inTaxRate the value for t_item_info.in_tax_rate
     *
     * @mbggenerated
     */
    public void setInTaxRate(BigDecimal inTaxRate) {
        this.inTaxRate = inTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.out_tax_rate
     *
     * @return the value of t_item_info.out_tax_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOutTaxRate() {
        return outTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.out_tax_rate
     *
     * @param outTaxRate the value for t_item_info.out_tax_rate
     *
     * @mbggenerated
     */
    public void setOutTaxRate(BigDecimal outTaxRate) {
        this.outTaxRate = outTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_sale_rate
     *
     * @return the value of t_item_info.item_sale_rate
     *
     * @mbggenerated
     */
    public BigDecimal getItemSaleRate() {
        return itemSaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_sale_rate
     *
     * @param itemSaleRate the value for t_item_info.item_sale_rate
     *
     * @mbggenerated
     */
    public void setItemSaleRate(BigDecimal itemSaleRate) {
        this.itemSaleRate = itemSaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_pf_rate
     *
     * @return the value of t_item_info.item_pf_rate
     *
     * @mbggenerated
     */
    public BigDecimal getItemPfRate() {
        return itemPfRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_pf_rate
     *
     * @param itemPfRate the value for t_item_info.item_pf_rate
     *
     * @mbggenerated
     */
    public void setItemPfRate(BigDecimal itemPfRate) {
        this.itemPfRate = itemPfRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.integral_rate
     *
     * @return the value of t_item_info.integral_rate
     *
     * @mbggenerated
     */
    public BigDecimal getIntegralRate() {
        return integralRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.integral_rate
     *
     * @param integralRate the value for t_item_info.integral_rate
     *
     * @mbggenerated
     */
    public void setIntegralRate(BigDecimal integralRate) {
        this.integralRate = integralRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.cost_type
     *
     * @return the value of t_item_info.cost_type
     *
     * @mbggenerated
     */
    public String getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.cost_type
     *
     * @param costType the value for t_item_info.cost_type
     *
     * @mbggenerated
     */
    public void setCostType(String costType) {
        this.costType = costType == null ? null : costType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.display_flag
     *
     * @return the value of t_item_info.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.display_flag
     *
     * @param displayFlag the value for t_item_info.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.internal_flag
     *
     * @return the value of t_item_info.internal_flag
     *
     * @mbggenerated
     */
    public String getInternalFlag() {
        return internalFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.internal_flag
     *
     * @param internalFlag the value for t_item_info.internal_flag
     *
     * @mbggenerated
     */
    public void setInternalFlag(String internalFlag) {
        this.internalFlag = internalFlag == null ? null : internalFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_memo
     *
     * @return the value of t_item_info.item_memo
     *
     * @mbggenerated
     */
    public String getItemMemo() {
        return itemMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_memo
     *
     * @param itemMemo the value for t_item_info.item_memo
     *
     * @mbggenerated
     */
    public void setItemMemo(String itemMemo) {
        this.itemMemo = itemMemo == null ? null : itemMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bytxt1
     *
     * @return the value of t_item_info.item_bytxt1
     *
     * @mbggenerated
     */
    public String getItemBytxt1() {
        return itemBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bytxt1
     *
     * @param itemBytxt1 the value for t_item_info.item_bytxt1
     *
     * @mbggenerated
     */
    public void setItemBytxt1(String itemBytxt1) {
        this.itemBytxt1 = itemBytxt1 == null ? null : itemBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bytxt2
     *
     * @return the value of t_item_info.item_bytxt2
     *
     * @mbggenerated
     */
    public String getItemBytxt2() {
        return itemBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bytxt2
     *
     * @param itemBytxt2 the value for t_item_info.item_bytxt2
     *
     * @mbggenerated
     */
    public void setItemBytxt2(String itemBytxt2) {
        this.itemBytxt2 = itemBytxt2 == null ? null : itemBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bytxt3
     *
     * @return the value of t_item_info.item_bytxt3
     *
     * @mbggenerated
     */
    public String getItemBytxt3() {
        return itemBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bytxt3
     *
     * @param itemBytxt3 the value for t_item_info.item_bytxt3
     *
     * @mbggenerated
     */
    public void setItemBytxt3(String itemBytxt3) {
        this.itemBytxt3 = itemBytxt3 == null ? null : itemBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bynum1
     *
     * @return the value of t_item_info.item_bynum1
     *
     * @mbggenerated
     */
    public BigDecimal getItemBynum1() {
        return itemBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bynum1
     *
     * @param itemBynum1 the value for t_item_info.item_bynum1
     *
     * @mbggenerated
     */
    public void setItemBynum1(BigDecimal itemBynum1) {
        this.itemBynum1 = itemBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bynum2
     *
     * @return the value of t_item_info.item_bynum2
     *
     * @mbggenerated
     */
    public BigDecimal getItemBynum2() {
        return itemBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bynum2
     *
     * @param itemBynum2 the value for t_item_info.item_bynum2
     *
     * @mbggenerated
     */
    public void setItemBynum2(BigDecimal itemBynum2) {
        this.itemBynum2 = itemBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_bynum3
     *
     * @return the value of t_item_info.item_bynum3
     *
     * @mbggenerated
     */
    public BigDecimal getItemBynum3() {
        return itemBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_bynum3
     *
     * @param itemBynum3 the value for t_item_info.item_bynum3
     *
     * @mbggenerated
     */
    public void setItemBynum3(BigDecimal itemBynum3) {
        this.itemBynum3 = itemBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.IsSysFlag
     *
     * @return the value of t_item_info.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.IsSysFlag
     *
     * @param issysflag the value for t_item_info.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.lock_user
     *
     * @return the value of t_item_info.lock_user
     *
     * @mbggenerated
     */
    public String getLockUser() {
        return lockUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.lock_user
     *
     * @param lockUser the value for t_item_info.lock_user
     *
     * @mbggenerated
     */
    public void setLockUser(String lockUser) {
        this.lockUser = lockUser == null ? null : lockUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.create_date
     *
     * @return the value of t_item_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.create_date
     *
     * @param createDate the value for t_item_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.create_user
     *
     * @return the value of t_item_info.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.create_user
     *
     * @param createUser the value for t_item_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.modify_date
     *
     * @return the value of t_item_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.modify_date
     *
     * @param modifyDate the value for t_item_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.modify_user
     *
     * @return the value of t_item_info.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.modify_user
     *
     * @param modifyUser the value for t_item_info.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.update_flow
     *
     * @return the value of t_item_info.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.update_flow
     *
     * @param updateFlow the value for t_item_info.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_sale_ratetype
     *
     * @return the value of t_item_info.item_sale_ratetype
     *
     * @mbggenerated
     */
    public String getItemSaleRatetype() {
        return itemSaleRatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_sale_ratetype
     *
     * @param itemSaleRatetype the value for t_item_info.item_sale_ratetype
     *
     * @mbggenerated
     */
    public void setItemSaleRatetype(String itemSaleRatetype) {
        this.itemSaleRatetype = itemSaleRatetype == null ? null : itemSaleRatetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_pf_ratetype
     *
     * @return the value of t_item_info.item_pf_ratetype
     *
     * @mbggenerated
     */
    public String getItemPfRatetype() {
        return itemPfRatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_pf_ratetype
     *
     * @param itemPfRatetype the value for t_item_info.item_pf_ratetype
     *
     * @mbggenerated
     */
    public void setItemPfRatetype(String itemPfRatetype) {
        this.itemPfRatetype = itemPfRatetype == null ? null : itemPfRatetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_date_unit
     *
     * @return the value of t_item_info.item_date_unit
     *
     * @mbggenerated
     */
    public String getItemDateUnit() {
        return itemDateUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_date_unit
     *
     * @param itemDateUnit the value for t_item_info.item_date_unit
     *
     * @mbggenerated
     */
    public void setItemDateUnit(String itemDateUnit) {
        this.itemDateUnit = itemDateUnit == null ? null : itemDateUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.showbox_no
     *
     * @return the value of t_item_info.showbox_no
     *
     * @mbggenerated
     */
    public String getShowboxNo() {
        return showboxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.showbox_no
     *
     * @param showboxNo the value for t_item_info.showbox_no
     *
     * @mbggenerated
     */
    public void setShowboxNo(String showboxNo) {
        this.showboxNo = showboxNo == null ? null : showboxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_in_ratetype
     *
     * @return the value of t_item_info.item_in_ratetype
     *
     * @mbggenerated
     */
    public String getItemInRatetype() {
        return itemInRatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_in_ratetype
     *
     * @param itemInRatetype the value for t_item_info.item_in_ratetype
     *
     * @mbggenerated
     */
    public void setItemInRatetype(String itemInRatetype) {
        this.itemInRatetype = itemInRatetype == null ? null : itemInRatetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_in_rate
     *
     * @return the value of t_item_info.item_in_rate
     *
     * @mbggenerated
     */
    public BigDecimal getItemInRate() {
        return itemInRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_in_rate
     *
     * @param itemInRate the value for t_item_info.item_in_rate
     *
     * @mbggenerated
     */
    public void setItemInRate(BigDecimal itemInRate) {
        this.itemInRate = itemInRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.branch_no
     *
     * @return the value of t_item_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.branch_no
     *
     * @param branchNo the value for t_item_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_IsGood
     *
     * @return the value of t_item_info.item_IsGood
     *
     * @mbggenerated
     */
    public String getItemIsgood() {
        return itemIsgood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_IsGood
     *
     * @param itemIsgood the value for t_item_info.item_IsGood
     *
     * @mbggenerated
     */
    public void setItemIsgood(String itemIsgood) {
        this.itemIsgood = itemIsgood == null ? null : itemIsgood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_abc
     *
     * @return the value of t_item_info.item_abc
     *
     * @mbggenerated
     */
    public String getItemAbc() {
        return itemAbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_abc
     *
     * @param itemAbc the value for t_item_info.item_abc
     *
     * @mbggenerated
     */
    public void setItemAbc(String itemAbc) {
        this.itemAbc = itemAbc == null ? null : itemAbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_print_label
     *
     * @return the value of t_item_info.item_print_label
     *
     * @mbggenerated
     */
    public String getItemPrintLabel() {
        return itemPrintLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_print_label
     *
     * @param itemPrintLabel the value for t_item_info.item_print_label
     *
     * @mbggenerated
     */
    public void setItemPrintLabel(String itemPrintLabel) {
        this.itemPrintLabel = itemPrintLabel == null ? null : itemPrintLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_qa_cert
     *
     * @return the value of t_item_info.item_qa_cert
     *
     * @mbggenerated
     */
    public String getItemQaCert() {
        return itemQaCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_qa_cert
     *
     * @param itemQaCert the value for t_item_info.item_qa_cert
     *
     * @mbggenerated
     */
    public void setItemQaCert(String itemQaCert) {
        this.itemQaCert = itemQaCert == null ? null : itemQaCert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_qs_cert
     *
     * @return the value of t_item_info.item_qs_cert
     *
     * @mbggenerated
     */
    public String getItemQsCert() {
        return itemQsCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_qs_cert
     *
     * @param itemQsCert the value for t_item_info.item_qs_cert
     *
     * @mbggenerated
     */
    public void setItemQsCert(String itemQsCert) {
        this.itemQsCert = itemQsCert == null ? null : itemQsCert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_inlet_cert
     *
     * @return the value of t_item_info.item_inlet_cert
     *
     * @mbggenerated
     */
    public String getItemInletCert() {
        return itemInletCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_inlet_cert
     *
     * @param itemInletCert the value for t_item_info.item_inlet_cert
     *
     * @mbggenerated
     */
    public void setItemInletCert(String itemInletCert) {
        this.itemInletCert = itemInletCert == null ? null : itemInletCert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_qi_rep
     *
     * @return the value of t_item_info.item_qi_rep
     *
     * @mbggenerated
     */
    public String getItemQiRep() {
        return itemQiRep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_qi_rep
     *
     * @param itemQiRep the value for t_item_info.item_qi_rep
     *
     * @mbggenerated
     */
    public void setItemQiRep(String itemQiRep) {
        this.itemQiRep = itemQiRep == null ? null : itemQiRep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.have_saleman
     *
     * @return the value of t_item_info.have_saleman
     *
     * @mbggenerated
     */
    public String getHaveSaleman() {
        return haveSaleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.have_saleman
     *
     * @param haveSaleman the value for t_item_info.have_saleman
     *
     * @mbggenerated
     */
    public void setHaveSaleman(String haveSaleman) {
        this.haveSaleman = haveSaleman == null ? null : haveSaleman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.update_time
     *
     * @return the value of t_item_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.update_time
     *
     * @param updateTime the value for t_item_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.update_branch
     *
     * @return the value of t_item_info.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.update_branch
     *
     * @param updateBranch the value for t_item_info.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_dist_qty
     *
     * @return the value of t_item_info.item_dist_qty
     *
     * @mbggenerated
     */
    public BigDecimal getItemDistQty() {
        return itemDistQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_dist_qty
     *
     * @param itemDistQty the value for t_item_info.item_dist_qty
     *
     * @mbggenerated
     */
    public void setItemDistQty(BigDecimal itemDistQty) {
        this.itemDistQty = itemDistQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_dist_limit
     *
     * @return the value of t_item_info.item_dist_limit
     *
     * @mbggenerated
     */
    public String getItemDistLimit() {
        return itemDistLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_dist_limit
     *
     * @param itemDistLimit the value for t_item_info.item_dist_limit
     *
     * @mbggenerated
     */
    public void setItemDistLimit(String itemDistLimit) {
        this.itemDistLimit = itemDistLimit == null ? null : itemDistLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_dist_double
     *
     * @return the value of t_item_info.item_dist_double
     *
     * @mbggenerated
     */
    public String getItemDistDouble() {
        return itemDistDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_dist_double
     *
     * @param itemDistDouble the value for t_item_info.item_dist_double
     *
     * @mbggenerated
     */
    public void setItemDistDouble(String itemDistDouble) {
        this.itemDistDouble = itemDistDouble == null ? null : itemDistDouble.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_pzwh
     *
     * @return the value of t_item_info.item_pzwh
     *
     * @mbggenerated
     */
    public String getItemPzwh() {
        return itemPzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_pzwh
     *
     * @param itemPzwh the value for t_item_info.item_pzwh
     *
     * @mbggenerated
     */
    public void setItemPzwh(String itemPzwh) {
        this.itemPzwh = itemPzwh == null ? null : itemPzwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_factory
     *
     * @return the value of t_item_info.item_factory
     *
     * @mbggenerated
     */
    public String getItemFactory() {
        return itemFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_factory
     *
     * @param itemFactory the value for t_item_info.item_factory
     *
     * @mbggenerated
     */
    public void setItemFactory(String itemFactory) {
        this.itemFactory = itemFactory == null ? null : itemFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_sys_memo1
     *
     * @return the value of t_item_info.item_sys_memo1
     *
     * @mbggenerated
     */
    public String getItemSysMemo1() {
        return itemSysMemo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_sys_memo1
     *
     * @param itemSysMemo1 the value for t_item_info.item_sys_memo1
     *
     * @mbggenerated
     */
    public void setItemSysMemo1(String itemSysMemo1) {
        this.itemSysMemo1 = itemSysMemo1 == null ? null : itemSysMemo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.have_salememo
     *
     * @return the value of t_item_info.have_salememo
     *
     * @mbggenerated
     */
    public String getHaveSalememo() {
        return haveSalememo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.have_salememo
     *
     * @param haveSalememo the value for t_item_info.have_salememo
     *
     * @mbggenerated
     */
    public void setHaveSalememo(String haveSalememo) {
        this.haveSalememo = haveSalememo == null ? null : haveSalememo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.buy_days
     *
     * @return the value of t_item_info.buy_days
     *
     * @mbggenerated
     */
    public Integer getBuyDays() {
        return buyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.buy_days
     *
     * @param buyDays the value for t_item_info.buy_days
     *
     * @mbggenerated
     */
    public void setBuyDays(Integer buyDays) {
        this.buyDays = buyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.pos_limit_qty
     *
     * @return the value of t_item_info.pos_limit_qty
     *
     * @mbggenerated
     */
    public BigDecimal getPosLimitQty() {
        return posLimitQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.pos_limit_qty
     *
     * @param posLimitQty the value for t_item_info.pos_limit_qty
     *
     * @mbggenerated
     */
    public void setPosLimitQty(BigDecimal posLimitQty) {
        this.posLimitQty = posLimitQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_yp_flag
     *
     * @return the value of t_item_info.item_yp_flag
     *
     * @mbggenerated
     */
    public String getItemYpFlag() {
        return itemYpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_yp_flag
     *
     * @param itemYpFlag the value for t_item_info.item_yp_flag
     *
     * @mbggenerated
     */
    public void setItemYpFlag(String itemYpFlag) {
        this.itemYpFlag = itemYpFlag == null ? null : itemYpFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.eshop_Integral
     *
     * @return the value of t_item_info.eshop_Integral
     *
     * @mbggenerated
     */
    public BigDecimal getEshopIntegral() {
        return eshopIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.eshop_Integral
     *
     * @param eshopIntegral the value for t_item_info.eshop_Integral
     *
     * @mbggenerated
     */
    public void setEshopIntegral(BigDecimal eshopIntegral) {
        this.eshopIntegral = eshopIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.trans_upflag
     *
     * @return the value of t_item_info.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.trans_upflag
     *
     * @param transUpflag the value for t_item_info.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_jj
     *
     * @return the value of t_item_info.item_jj
     *
     * @mbggenerated
     */
    public String getItemJj() {
        return itemJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_jj
     *
     * @param itemJj the value for t_item_info.item_jj
     *
     * @mbggenerated
     */
    public void setItemJj(String itemJj) {
        this.itemJj = itemJj == null ? null : itemJj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_info.item_ks
     *
     * @return the value of t_item_info.item_ks
     *
     * @mbggenerated
     */
    public String getItemKs() {
        return itemKs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_info.item_ks
     *
     * @param itemKs the value for t_item_info.item_ks
     *
     * @mbggenerated
     */
    public void setItemKs(String itemKs) {
        this.itemKs = itemKs == null ? null : itemKs.trim();
    }
}