package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TItemClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.item_class
     *
     * @mbggenerated
     */
    private String itemClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.class_data
     *
     * @mbggenerated
     */
    private String classData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.price_type
     *
     * @mbggenerated
     */
    private String priceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.sale_price_rate
     *
     * @mbggenerated
     */
    private BigDecimal salePriceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.pf_price_rate
     *
     * @mbggenerated
     */
    private BigDecimal pfPriceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.vip_price_rate
     *
     * @mbggenerated
     */
    private BigDecimal vipPriceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.edible_flag
     *
     * @mbggenerated
     */
    private String edibleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.create_man
     *
     * @mbggenerated
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.modify_man
     *
     * @mbggenerated
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.limit_max_qty
     *
     * @mbggenerated
     */
    private BigDecimal limitMaxQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.limit_min_qty
     *
     * @mbggenerated
     */
    private BigDecimal limitMinQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_class.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.item_class
     *
     * @return the value of t_item_class.item_class
     *
     * @mbggenerated
     */
    public String getItemClass() {
        return itemClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.item_class
     *
     * @param itemClass the value for t_item_class.item_class
     *
     * @mbggenerated
     */
    public void setItemClass(String itemClass) {
        this.itemClass = itemClass == null ? null : itemClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.class_name
     *
     * @return the value of t_item_class.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.class_name
     *
     * @param className the value for t_item_class.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.class_data
     *
     * @return the value of t_item_class.class_data
     *
     * @mbggenerated
     */
    public String getClassData() {
        return classData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.class_data
     *
     * @param classData the value for t_item_class.class_data
     *
     * @mbggenerated
     */
    public void setClassData(String classData) {
        this.classData = classData == null ? null : classData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.price_type
     *
     * @return the value of t_item_class.price_type
     *
     * @mbggenerated
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.price_type
     *
     * @param priceType the value for t_item_class.price_type
     *
     * @mbggenerated
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.sale_price_rate
     *
     * @return the value of t_item_class.sale_price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSalePriceRate() {
        return salePriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.sale_price_rate
     *
     * @param salePriceRate the value for t_item_class.sale_price_rate
     *
     * @mbggenerated
     */
    public void setSalePriceRate(BigDecimal salePriceRate) {
        this.salePriceRate = salePriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.pf_price_rate
     *
     * @return the value of t_item_class.pf_price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPfPriceRate() {
        return pfPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.pf_price_rate
     *
     * @param pfPriceRate the value for t_item_class.pf_price_rate
     *
     * @mbggenerated
     */
    public void setPfPriceRate(BigDecimal pfPriceRate) {
        this.pfPriceRate = pfPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.vip_price_rate
     *
     * @return the value of t_item_class.vip_price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getVipPriceRate() {
        return vipPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.vip_price_rate
     *
     * @param vipPriceRate the value for t_item_class.vip_price_rate
     *
     * @mbggenerated
     */
    public void setVipPriceRate(BigDecimal vipPriceRate) {
        this.vipPriceRate = vipPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.edible_flag
     *
     * @return the value of t_item_class.edible_flag
     *
     * @mbggenerated
     */
    public String getEdibleFlag() {
        return edibleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.edible_flag
     *
     * @param edibleFlag the value for t_item_class.edible_flag
     *
     * @mbggenerated
     */
    public void setEdibleFlag(String edibleFlag) {
        this.edibleFlag = edibleFlag == null ? null : edibleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.IsSysFlag
     *
     * @return the value of t_item_class.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.IsSysFlag
     *
     * @param issysflag the value for t_item_class.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.update_flow
     *
     * @return the value of t_item_class.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.update_flow
     *
     * @param updateFlow the value for t_item_class.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.update_time
     *
     * @return the value of t_item_class.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.update_time
     *
     * @param updateTime the value for t_item_class.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.update_branch
     *
     * @return the value of t_item_class.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.update_branch
     *
     * @param updateBranch the value for t_item_class.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.create_date
     *
     * @return the value of t_item_class.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.create_date
     *
     * @param createDate the value for t_item_class.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.create_man
     *
     * @return the value of t_item_class.create_man
     *
     * @mbggenerated
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.create_man
     *
     * @param createMan the value for t_item_class.create_man
     *
     * @mbggenerated
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.modify_date
     *
     * @return the value of t_item_class.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.modify_date
     *
     * @param modifyDate the value for t_item_class.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.modify_man
     *
     * @return the value of t_item_class.modify_man
     *
     * @mbggenerated
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.modify_man
     *
     * @param modifyMan the value for t_item_class.modify_man
     *
     * @mbggenerated
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.limit_max_qty
     *
     * @return the value of t_item_class.limit_max_qty
     *
     * @mbggenerated
     */
    public BigDecimal getLimitMaxQty() {
        return limitMaxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.limit_max_qty
     *
     * @param limitMaxQty the value for t_item_class.limit_max_qty
     *
     * @mbggenerated
     */
    public void setLimitMaxQty(BigDecimal limitMaxQty) {
        this.limitMaxQty = limitMaxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.limit_min_qty
     *
     * @return the value of t_item_class.limit_min_qty
     *
     * @mbggenerated
     */
    public BigDecimal getLimitMinQty() {
        return limitMinQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.limit_min_qty
     *
     * @param limitMinQty the value for t_item_class.limit_min_qty
     *
     * @mbggenerated
     */
    public void setLimitMinQty(BigDecimal limitMinQty) {
        this.limitMinQty = limitMinQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_class.trans_upflag
     *
     * @return the value of t_item_class.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_class.trans_upflag
     *
     * @param transUpflag the value for t_item_class.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }
}