package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TPosSaleMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.sheet_no
     *
     * @mbggenerated
     */
    private String sheetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.sale_time
     *
     * @mbggenerated
     */
    private Date saleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_type
     *
     * @mbggenerated
     */
    private String posType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_status
     *
     * @mbggenerated
     */
    private String posStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.deal_no
     *
     * @mbggenerated
     */
    private String dealNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.deal_class
     *
     * @mbggenerated
     */
    private String dealClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.counter_no
     *
     * @mbggenerated
     */
    private String counterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.jh
     *
     * @mbggenerated
     */
    private String jh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.local_no
     *
     * @mbggenerated
     */
    private String localNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.work_no
     *
     * @mbggenerated
     */
    private String workNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.voucher_no
     *
     * @mbggenerated
     */
    private String voucherNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.vip_no
     *
     * @mbggenerated
     */
    private String vipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_org_amt
     *
     * @mbggenerated
     */
    private BigDecimal posOrgAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_total_amt
     *
     * @mbggenerated
     */
    private BigDecimal posTotalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_integral
     *
     * @mbggenerated
     */
    private BigDecimal posIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_man
     *
     * @mbggenerated
     */
    private String custMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_address
     *
     * @mbggenerated
     */
    private String custAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_tel
     *
     * @mbggenerated
     */
    private String custTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_request
     *
     * @mbggenerated
     */
    private String custRequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_order_time
     *
     * @mbggenerated
     */
    private Date posOrderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_send_time
     *
     * @mbggenerated
     */
    private Date posSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.deal_order
     *
     * @mbggenerated
     */
    private String dealOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_memo
     *
     * @mbggenerated
     */
    private String posMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_bytxt1
     *
     * @mbggenerated
     */
    private String posBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_bytxt2
     *
     * @mbggenerated
     */
    private String posBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_bytxt3
     *
     * @mbggenerated
     */
    private String posBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.fu_times
     *
     * @mbggenerated
     */
    private Integer fuTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_order_IsSend
     *
     * @mbggenerated
     */
    private String posOrderIssend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_order_status
     *
     * @mbggenerated
     */
    private String posOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.pos_order_sender
     *
     * @mbggenerated
     */
    private String posOrderSender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_no
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.tour_grp
     *
     * @mbggenerated
     */
    private String tourGrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.tour_no
     *
     * @mbggenerated
     */
    private String tourNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.guide_no
     *
     * @mbggenerated
     */
    private String guideNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_sex
     *
     * @mbggenerated
     */
    private String custSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_id
     *
     * @mbggenerated
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cust_age
     *
     * @mbggenerated
     */
    private String custAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_from
     *
     * @mbggenerated
     */
    private String cfFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_ys
     *
     * @mbggenerated
     */
    private String cfYs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_pyr
     *
     * @mbggenerated
     */
    private String cfPyr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_fyr
     *
     * @mbggenerated
     */
    private String cfFyr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_zd
     *
     * @mbggenerated
     */
    private String cfZd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_master.cf_no
     *
     * @mbggenerated
     */
    private String cfNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.sheet_no
     *
     * @return the value of t_pos_sale_master.sheet_no
     *
     * @mbggenerated
     */
    public String getSheetNo() {
        return sheetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.sheet_no
     *
     * @param sheetNo the value for t_pos_sale_master.sheet_no
     *
     * @mbggenerated
     */
    public void setSheetNo(String sheetNo) {
        this.sheetNo = sheetNo == null ? null : sheetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.oper_date
     *
     * @return the value of t_pos_sale_master.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.oper_date
     *
     * @param operDate the value for t_pos_sale_master.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.sale_time
     *
     * @return the value of t_pos_sale_master.sale_time
     *
     * @mbggenerated
     */
    public Date getSaleTime() {
        return saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.sale_time
     *
     * @param saleTime the value for t_pos_sale_master.sale_time
     *
     * @mbggenerated
     */
    public void setSaleTime(Date saleTime) {
        this.saleTime = saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_type
     *
     * @return the value of t_pos_sale_master.pos_type
     *
     * @mbggenerated
     */
    public String getPosType() {
        return posType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_type
     *
     * @param posType the value for t_pos_sale_master.pos_type
     *
     * @mbggenerated
     */
    public void setPosType(String posType) {
        this.posType = posType == null ? null : posType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_status
     *
     * @return the value of t_pos_sale_master.pos_status
     *
     * @mbggenerated
     */
    public String getPosStatus() {
        return posStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_status
     *
     * @param posStatus the value for t_pos_sale_master.pos_status
     *
     * @mbggenerated
     */
    public void setPosStatus(String posStatus) {
        this.posStatus = posStatus == null ? null : posStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.deal_no
     *
     * @return the value of t_pos_sale_master.deal_no
     *
     * @mbggenerated
     */
    public String getDealNo() {
        return dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.deal_no
     *
     * @param dealNo the value for t_pos_sale_master.deal_no
     *
     * @mbggenerated
     */
    public void setDealNo(String dealNo) {
        this.dealNo = dealNo == null ? null : dealNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.deal_class
     *
     * @return the value of t_pos_sale_master.deal_class
     *
     * @mbggenerated
     */
    public String getDealClass() {
        return dealClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.deal_class
     *
     * @param dealClass the value for t_pos_sale_master.deal_class
     *
     * @mbggenerated
     */
    public void setDealClass(String dealClass) {
        this.dealClass = dealClass == null ? null : dealClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.user_id
     *
     * @return the value of t_pos_sale_master.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.user_id
     *
     * @param userId the value for t_pos_sale_master.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.branch_no
     *
     * @return the value of t_pos_sale_master.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.branch_no
     *
     * @param branchNo the value for t_pos_sale_master.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.counter_no
     *
     * @return the value of t_pos_sale_master.counter_no
     *
     * @mbggenerated
     */
    public String getCounterNo() {
        return counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.counter_no
     *
     * @param counterNo the value for t_pos_sale_master.counter_no
     *
     * @mbggenerated
     */
    public void setCounterNo(String counterNo) {
        this.counterNo = counterNo == null ? null : counterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.jh
     *
     * @return the value of t_pos_sale_master.jh
     *
     * @mbggenerated
     */
    public String getJh() {
        return jh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.jh
     *
     * @param jh the value for t_pos_sale_master.jh
     *
     * @mbggenerated
     */
    public void setJh(String jh) {
        this.jh = jh == null ? null : jh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.local_no
     *
     * @return the value of t_pos_sale_master.local_no
     *
     * @mbggenerated
     */
    public String getLocalNo() {
        return localNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.local_no
     *
     * @param localNo the value for t_pos_sale_master.local_no
     *
     * @mbggenerated
     */
    public void setLocalNo(String localNo) {
        this.localNo = localNo == null ? null : localNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.work_no
     *
     * @return the value of t_pos_sale_master.work_no
     *
     * @mbggenerated
     */
    public String getWorkNo() {
        return workNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.work_no
     *
     * @param workNo the value for t_pos_sale_master.work_no
     *
     * @mbggenerated
     */
    public void setWorkNo(String workNo) {
        this.workNo = workNo == null ? null : workNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.voucher_no
     *
     * @return the value of t_pos_sale_master.voucher_no
     *
     * @mbggenerated
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.voucher_no
     *
     * @param voucherNo the value for t_pos_sale_master.voucher_no
     *
     * @mbggenerated
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo == null ? null : voucherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.vip_no
     *
     * @return the value of t_pos_sale_master.vip_no
     *
     * @mbggenerated
     */
    public String getVipNo() {
        return vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.vip_no
     *
     * @param vipNo the value for t_pos_sale_master.vip_no
     *
     * @mbggenerated
     */
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo == null ? null : vipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_org_amt
     *
     * @return the value of t_pos_sale_master.pos_org_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPosOrgAmt() {
        return posOrgAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_org_amt
     *
     * @param posOrgAmt the value for t_pos_sale_master.pos_org_amt
     *
     * @mbggenerated
     */
    public void setPosOrgAmt(BigDecimal posOrgAmt) {
        this.posOrgAmt = posOrgAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_total_amt
     *
     * @return the value of t_pos_sale_master.pos_total_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPosTotalAmt() {
        return posTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_total_amt
     *
     * @param posTotalAmt the value for t_pos_sale_master.pos_total_amt
     *
     * @mbggenerated
     */
    public void setPosTotalAmt(BigDecimal posTotalAmt) {
        this.posTotalAmt = posTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_integral
     *
     * @return the value of t_pos_sale_master.pos_integral
     *
     * @mbggenerated
     */
    public BigDecimal getPosIntegral() {
        return posIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_integral
     *
     * @param posIntegral the value for t_pos_sale_master.pos_integral
     *
     * @mbggenerated
     */
    public void setPosIntegral(BigDecimal posIntegral) {
        this.posIntegral = posIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_name
     *
     * @return the value of t_pos_sale_master.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_name
     *
     * @param custName the value for t_pos_sale_master.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_man
     *
     * @return the value of t_pos_sale_master.cust_man
     *
     * @mbggenerated
     */
    public String getCustMan() {
        return custMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_man
     *
     * @param custMan the value for t_pos_sale_master.cust_man
     *
     * @mbggenerated
     */
    public void setCustMan(String custMan) {
        this.custMan = custMan == null ? null : custMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_address
     *
     * @return the value of t_pos_sale_master.cust_address
     *
     * @mbggenerated
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_address
     *
     * @param custAddress the value for t_pos_sale_master.cust_address
     *
     * @mbggenerated
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_tel
     *
     * @return the value of t_pos_sale_master.cust_tel
     *
     * @mbggenerated
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_tel
     *
     * @param custTel the value for t_pos_sale_master.cust_tel
     *
     * @mbggenerated
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_request
     *
     * @return the value of t_pos_sale_master.cust_request
     *
     * @mbggenerated
     */
    public String getCustRequest() {
        return custRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_request
     *
     * @param custRequest the value for t_pos_sale_master.cust_request
     *
     * @mbggenerated
     */
    public void setCustRequest(String custRequest) {
        this.custRequest = custRequest == null ? null : custRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_order_time
     *
     * @return the value of t_pos_sale_master.pos_order_time
     *
     * @mbggenerated
     */
    public Date getPosOrderTime() {
        return posOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_order_time
     *
     * @param posOrderTime the value for t_pos_sale_master.pos_order_time
     *
     * @mbggenerated
     */
    public void setPosOrderTime(Date posOrderTime) {
        this.posOrderTime = posOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_send_time
     *
     * @return the value of t_pos_sale_master.pos_send_time
     *
     * @mbggenerated
     */
    public Date getPosSendTime() {
        return posSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_send_time
     *
     * @param posSendTime the value for t_pos_sale_master.pos_send_time
     *
     * @mbggenerated
     */
    public void setPosSendTime(Date posSendTime) {
        this.posSendTime = posSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.deal_order
     *
     * @return the value of t_pos_sale_master.deal_order
     *
     * @mbggenerated
     */
    public String getDealOrder() {
        return dealOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.deal_order
     *
     * @param dealOrder the value for t_pos_sale_master.deal_order
     *
     * @mbggenerated
     */
    public void setDealOrder(String dealOrder) {
        this.dealOrder = dealOrder == null ? null : dealOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_memo
     *
     * @return the value of t_pos_sale_master.pos_memo
     *
     * @mbggenerated
     */
    public String getPosMemo() {
        return posMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_memo
     *
     * @param posMemo the value for t_pos_sale_master.pos_memo
     *
     * @mbggenerated
     */
    public void setPosMemo(String posMemo) {
        this.posMemo = posMemo == null ? null : posMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_bytxt1
     *
     * @return the value of t_pos_sale_master.pos_bytxt1
     *
     * @mbggenerated
     */
    public String getPosBytxt1() {
        return posBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_bytxt1
     *
     * @param posBytxt1 the value for t_pos_sale_master.pos_bytxt1
     *
     * @mbggenerated
     */
    public void setPosBytxt1(String posBytxt1) {
        this.posBytxt1 = posBytxt1 == null ? null : posBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_bytxt2
     *
     * @return the value of t_pos_sale_master.pos_bytxt2
     *
     * @mbggenerated
     */
    public String getPosBytxt2() {
        return posBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_bytxt2
     *
     * @param posBytxt2 the value for t_pos_sale_master.pos_bytxt2
     *
     * @mbggenerated
     */
    public void setPosBytxt2(String posBytxt2) {
        this.posBytxt2 = posBytxt2 == null ? null : posBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_bytxt3
     *
     * @return the value of t_pos_sale_master.pos_bytxt3
     *
     * @mbggenerated
     */
    public String getPosBytxt3() {
        return posBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_bytxt3
     *
     * @param posBytxt3 the value for t_pos_sale_master.pos_bytxt3
     *
     * @mbggenerated
     */
    public void setPosBytxt3(String posBytxt3) {
        this.posBytxt3 = posBytxt3 == null ? null : posBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.update_flow
     *
     * @return the value of t_pos_sale_master.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.update_flow
     *
     * @param updateFlow the value for t_pos_sale_master.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.update_time
     *
     * @return the value of t_pos_sale_master.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.update_time
     *
     * @param updateTime the value for t_pos_sale_master.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.update_branch
     *
     * @return the value of t_pos_sale_master.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.update_branch
     *
     * @param updateBranch the value for t_pos_sale_master.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.trans_upflag
     *
     * @return the value of t_pos_sale_master.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.trans_upflag
     *
     * @param transUpflag the value for t_pos_sale_master.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.fu_times
     *
     * @return the value of t_pos_sale_master.fu_times
     *
     * @mbggenerated
     */
    public Integer getFuTimes() {
        return fuTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.fu_times
     *
     * @param fuTimes the value for t_pos_sale_master.fu_times
     *
     * @mbggenerated
     */
    public void setFuTimes(Integer fuTimes) {
        this.fuTimes = fuTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_order_IsSend
     *
     * @return the value of t_pos_sale_master.pos_order_IsSend
     *
     * @mbggenerated
     */
    public String getPosOrderIssend() {
        return posOrderIssend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_order_IsSend
     *
     * @param posOrderIssend the value for t_pos_sale_master.pos_order_IsSend
     *
     * @mbggenerated
     */
    public void setPosOrderIssend(String posOrderIssend) {
        this.posOrderIssend = posOrderIssend == null ? null : posOrderIssend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_order_status
     *
     * @return the value of t_pos_sale_master.pos_order_status
     *
     * @mbggenerated
     */
    public String getPosOrderStatus() {
        return posOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_order_status
     *
     * @param posOrderStatus the value for t_pos_sale_master.pos_order_status
     *
     * @mbggenerated
     */
    public void setPosOrderStatus(String posOrderStatus) {
        this.posOrderStatus = posOrderStatus == null ? null : posOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.pos_order_sender
     *
     * @return the value of t_pos_sale_master.pos_order_sender
     *
     * @mbggenerated
     */
    public String getPosOrderSender() {
        return posOrderSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.pos_order_sender
     *
     * @param posOrderSender the value for t_pos_sale_master.pos_order_sender
     *
     * @mbggenerated
     */
    public void setPosOrderSender(String posOrderSender) {
        this.posOrderSender = posOrderSender == null ? null : posOrderSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_no
     *
     * @return the value of t_pos_sale_master.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_no
     *
     * @param custNo the value for t_pos_sale_master.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.tour_grp
     *
     * @return the value of t_pos_sale_master.tour_grp
     *
     * @mbggenerated
     */
    public String getTourGrp() {
        return tourGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.tour_grp
     *
     * @param tourGrp the value for t_pos_sale_master.tour_grp
     *
     * @mbggenerated
     */
    public void setTourGrp(String tourGrp) {
        this.tourGrp = tourGrp == null ? null : tourGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.tour_no
     *
     * @return the value of t_pos_sale_master.tour_no
     *
     * @mbggenerated
     */
    public String getTourNo() {
        return tourNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.tour_no
     *
     * @param tourNo the value for t_pos_sale_master.tour_no
     *
     * @mbggenerated
     */
    public void setTourNo(String tourNo) {
        this.tourNo = tourNo == null ? null : tourNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.guide_no
     *
     * @return the value of t_pos_sale_master.guide_no
     *
     * @mbggenerated
     */
    public String getGuideNo() {
        return guideNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.guide_no
     *
     * @param guideNo the value for t_pos_sale_master.guide_no
     *
     * @mbggenerated
     */
    public void setGuideNo(String guideNo) {
        this.guideNo = guideNo == null ? null : guideNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_sex
     *
     * @return the value of t_pos_sale_master.cust_sex
     *
     * @mbggenerated
     */
    public String getCustSex() {
        return custSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_sex
     *
     * @param custSex the value for t_pos_sale_master.cust_sex
     *
     * @mbggenerated
     */
    public void setCustSex(String custSex) {
        this.custSex = custSex == null ? null : custSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_id
     *
     * @return the value of t_pos_sale_master.cust_id
     *
     * @mbggenerated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_id
     *
     * @param custId the value for t_pos_sale_master.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cust_age
     *
     * @return the value of t_pos_sale_master.cust_age
     *
     * @mbggenerated
     */
    public String getCustAge() {
        return custAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cust_age
     *
     * @param custAge the value for t_pos_sale_master.cust_age
     *
     * @mbggenerated
     */
    public void setCustAge(String custAge) {
        this.custAge = custAge == null ? null : custAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_from
     *
     * @return the value of t_pos_sale_master.cf_from
     *
     * @mbggenerated
     */
    public String getCfFrom() {
        return cfFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_from
     *
     * @param cfFrom the value for t_pos_sale_master.cf_from
     *
     * @mbggenerated
     */
    public void setCfFrom(String cfFrom) {
        this.cfFrom = cfFrom == null ? null : cfFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_ys
     *
     * @return the value of t_pos_sale_master.cf_ys
     *
     * @mbggenerated
     */
    public String getCfYs() {
        return cfYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_ys
     *
     * @param cfYs the value for t_pos_sale_master.cf_ys
     *
     * @mbggenerated
     */
    public void setCfYs(String cfYs) {
        this.cfYs = cfYs == null ? null : cfYs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_pyr
     *
     * @return the value of t_pos_sale_master.cf_pyr
     *
     * @mbggenerated
     */
    public String getCfPyr() {
        return cfPyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_pyr
     *
     * @param cfPyr the value for t_pos_sale_master.cf_pyr
     *
     * @mbggenerated
     */
    public void setCfPyr(String cfPyr) {
        this.cfPyr = cfPyr == null ? null : cfPyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_fyr
     *
     * @return the value of t_pos_sale_master.cf_fyr
     *
     * @mbggenerated
     */
    public String getCfFyr() {
        return cfFyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_fyr
     *
     * @param cfFyr the value for t_pos_sale_master.cf_fyr
     *
     * @mbggenerated
     */
    public void setCfFyr(String cfFyr) {
        this.cfFyr = cfFyr == null ? null : cfFyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_zd
     *
     * @return the value of t_pos_sale_master.cf_zd
     *
     * @mbggenerated
     */
    public String getCfZd() {
        return cfZd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_zd
     *
     * @param cfZd the value for t_pos_sale_master.cf_zd
     *
     * @mbggenerated
     */
    public void setCfZd(String cfZd) {
        this.cfZd = cfZd == null ? null : cfZd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_master.cf_no
     *
     * @return the value of t_pos_sale_master.cf_no
     *
     * @mbggenerated
     */
    public String getCfNo() {
        return cfNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_master.cf_no
     *
     * @param cfNo the value for t_pos_sale_master.cf_no
     *
     * @mbggenerated
     */
    public void setCfNo(String cfNo) {
        this.cfNo = cfNo == null ? null : cfNo.trim();
    }
}