package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TPosSaleDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sheet_no
     *
     * @mbggenerated
     */
    private String sheetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sheet_sort
     *
     * @mbggenerated
     */
    private Integer sheetSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_barcode
     *
     * @mbggenerated
     */
    private String saleBarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.item_unit
     *
     * @mbggenerated
     */
    private String itemUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.unit_type
     *
     * @mbggenerated
     */
    private Integer unitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.unit_pack
     *
     * @mbggenerated
     */
    private BigDecimal unitPack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.org_price
     *
     * @mbggenerated
     */
    private BigDecimal orgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.real_price
     *
     * @mbggenerated
     */
    private BigDecimal realPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_qty
     *
     * @mbggenerated
     */
    private BigDecimal saleQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_sign
     *
     * @mbggenerated
     */
    private Integer saleSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_amt
     *
     * @mbggenerated
     */
    private BigDecimal saleAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_man
     *
     * @mbggenerated
     */
    private String saleMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.counter_no
     *
     * @mbggenerated
     */
    private String counterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.manage_type
     *
     * @mbggenerated
     */
    private String manageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.special_type
     *
     * @mbggenerated
     */
    private String specialType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.special_no
     *
     * @mbggenerated
     */
    private String specialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.item_ispack
     *
     * @mbggenerated
     */
    private String itemIspack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.js_qty
     *
     * @mbggenerated
     */
    private BigDecimal jsQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_memo
     *
     * @mbggenerated
     */
    private String saleMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bytxt1
     *
     * @mbggenerated
     */
    private String saleBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bytxt2
     *
     * @mbggenerated
     */
    private String saleBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bytxt3
     *
     * @mbggenerated
     */
    private String saleBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bynum1
     *
     * @mbggenerated
     */
    private BigDecimal saleBynum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bynum2
     *
     * @mbggenerated
     */
    private BigDecimal saleBynum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.sale_bynum3
     *
     * @mbggenerated
     */
    private BigDecimal saleBynum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.allzk_fore_real_price
     *
     * @mbggenerated
     */
    private BigDecimal allzkForeRealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.allzk_fore_special_type
     *
     * @mbggenerated
     */
    private String allzkForeSpecialType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.Manage_ly_rate
     *
     * @mbggenerated
     */
    private BigDecimal manageLyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.ly_sup_no
     *
     * @mbggenerated
     */
    private String lySupNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.inside_tax_amt
     *
     * @mbggenerated
     */
    private BigDecimal insideTaxAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.is_package
     *
     * @mbggenerated
     */
    private String isPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.limit_branch
     *
     * @mbggenerated
     */
    private String limitBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.limit_times
     *
     * @mbggenerated
     */
    private String limitTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.limit_date
     *
     * @mbggenerated
     */
    private String limitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.valid_begin
     *
     * @mbggenerated
     */
    private Date validBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pos_sale_detail.valid_end
     *
     * @mbggenerated
     */
    private Date validEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sheet_no
     *
     * @return the value of t_pos_sale_detail.sheet_no
     *
     * @mbggenerated
     */
    public String getSheetNo() {
        return sheetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sheet_no
     *
     * @param sheetNo the value for t_pos_sale_detail.sheet_no
     *
     * @mbggenerated
     */
    public void setSheetNo(String sheetNo) {
        this.sheetNo = sheetNo == null ? null : sheetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sheet_sort
     *
     * @return the value of t_pos_sale_detail.sheet_sort
     *
     * @mbggenerated
     */
    public Integer getSheetSort() {
        return sheetSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sheet_sort
     *
     * @param sheetSort the value for t_pos_sale_detail.sheet_sort
     *
     * @mbggenerated
     */
    public void setSheetSort(Integer sheetSort) {
        this.sheetSort = sheetSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.item_no
     *
     * @return the value of t_pos_sale_detail.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.item_no
     *
     * @param itemNo the value for t_pos_sale_detail.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_barcode
     *
     * @return the value of t_pos_sale_detail.sale_barcode
     *
     * @mbggenerated
     */
    public String getSaleBarcode() {
        return saleBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_barcode
     *
     * @param saleBarcode the value for t_pos_sale_detail.sale_barcode
     *
     * @mbggenerated
     */
    public void setSaleBarcode(String saleBarcode) {
        this.saleBarcode = saleBarcode == null ? null : saleBarcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.item_unit
     *
     * @return the value of t_pos_sale_detail.item_unit
     *
     * @mbggenerated
     */
    public String getItemUnit() {
        return itemUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.item_unit
     *
     * @param itemUnit the value for t_pos_sale_detail.item_unit
     *
     * @mbggenerated
     */
    public void setItemUnit(String itemUnit) {
        this.itemUnit = itemUnit == null ? null : itemUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.unit_type
     *
     * @return the value of t_pos_sale_detail.unit_type
     *
     * @mbggenerated
     */
    public Integer getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.unit_type
     *
     * @param unitType the value for t_pos_sale_detail.unit_type
     *
     * @mbggenerated
     */
    public void setUnitType(Integer unitType) {
        this.unitType = unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.unit_pack
     *
     * @return the value of t_pos_sale_detail.unit_pack
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPack() {
        return unitPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.unit_pack
     *
     * @param unitPack the value for t_pos_sale_detail.unit_pack
     *
     * @mbggenerated
     */
    public void setUnitPack(BigDecimal unitPack) {
        this.unitPack = unitPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.org_price
     *
     * @return the value of t_pos_sale_detail.org_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrgPrice() {
        return orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.org_price
     *
     * @param orgPrice the value for t_pos_sale_detail.org_price
     *
     * @mbggenerated
     */
    public void setOrgPrice(BigDecimal orgPrice) {
        this.orgPrice = orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.real_price
     *
     * @return the value of t_pos_sale_detail.real_price
     *
     * @mbggenerated
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.real_price
     *
     * @param realPrice the value for t_pos_sale_detail.real_price
     *
     * @mbggenerated
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_qty
     *
     * @return the value of t_pos_sale_detail.sale_qty
     *
     * @mbggenerated
     */
    public BigDecimal getSaleQty() {
        return saleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_qty
     *
     * @param saleQty the value for t_pos_sale_detail.sale_qty
     *
     * @mbggenerated
     */
    public void setSaleQty(BigDecimal saleQty) {
        this.saleQty = saleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_sign
     *
     * @return the value of t_pos_sale_detail.sale_sign
     *
     * @mbggenerated
     */
    public Integer getSaleSign() {
        return saleSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_sign
     *
     * @param saleSign the value for t_pos_sale_detail.sale_sign
     *
     * @mbggenerated
     */
    public void setSaleSign(Integer saleSign) {
        this.saleSign = saleSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_amt
     *
     * @return the value of t_pos_sale_detail.sale_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSaleAmt() {
        return saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_amt
     *
     * @param saleAmt the value for t_pos_sale_detail.sale_amt
     *
     * @mbggenerated
     */
    public void setSaleAmt(BigDecimal saleAmt) {
        this.saleAmt = saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_man
     *
     * @return the value of t_pos_sale_detail.sale_man
     *
     * @mbggenerated
     */
    public String getSaleMan() {
        return saleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_man
     *
     * @param saleMan the value for t_pos_sale_detail.sale_man
     *
     * @mbggenerated
     */
    public void setSaleMan(String saleMan) {
        this.saleMan = saleMan == null ? null : saleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.counter_no
     *
     * @return the value of t_pos_sale_detail.counter_no
     *
     * @mbggenerated
     */
    public String getCounterNo() {
        return counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.counter_no
     *
     * @param counterNo the value for t_pos_sale_detail.counter_no
     *
     * @mbggenerated
     */
    public void setCounterNo(String counterNo) {
        this.counterNo = counterNo == null ? null : counterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.manage_type
     *
     * @return the value of t_pos_sale_detail.manage_type
     *
     * @mbggenerated
     */
    public String getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.manage_type
     *
     * @param manageType the value for t_pos_sale_detail.manage_type
     *
     * @mbggenerated
     */
    public void setManageType(String manageType) {
        this.manageType = manageType == null ? null : manageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.special_type
     *
     * @return the value of t_pos_sale_detail.special_type
     *
     * @mbggenerated
     */
    public String getSpecialType() {
        return specialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.special_type
     *
     * @param specialType the value for t_pos_sale_detail.special_type
     *
     * @mbggenerated
     */
    public void setSpecialType(String specialType) {
        this.specialType = specialType == null ? null : specialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.special_no
     *
     * @return the value of t_pos_sale_detail.special_no
     *
     * @mbggenerated
     */
    public String getSpecialNo() {
        return specialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.special_no
     *
     * @param specialNo the value for t_pos_sale_detail.special_no
     *
     * @mbggenerated
     */
    public void setSpecialNo(String specialNo) {
        this.specialNo = specialNo == null ? null : specialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.item_ispack
     *
     * @return the value of t_pos_sale_detail.item_ispack
     *
     * @mbggenerated
     */
    public String getItemIspack() {
        return itemIspack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.item_ispack
     *
     * @param itemIspack the value for t_pos_sale_detail.item_ispack
     *
     * @mbggenerated
     */
    public void setItemIspack(String itemIspack) {
        this.itemIspack = itemIspack == null ? null : itemIspack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.js_qty
     *
     * @return the value of t_pos_sale_detail.js_qty
     *
     * @mbggenerated
     */
    public BigDecimal getJsQty() {
        return jsQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.js_qty
     *
     * @param jsQty the value for t_pos_sale_detail.js_qty
     *
     * @mbggenerated
     */
    public void setJsQty(BigDecimal jsQty) {
        this.jsQty = jsQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_memo
     *
     * @return the value of t_pos_sale_detail.sale_memo
     *
     * @mbggenerated
     */
    public String getSaleMemo() {
        return saleMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_memo
     *
     * @param saleMemo the value for t_pos_sale_detail.sale_memo
     *
     * @mbggenerated
     */
    public void setSaleMemo(String saleMemo) {
        this.saleMemo = saleMemo == null ? null : saleMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bytxt1
     *
     * @return the value of t_pos_sale_detail.sale_bytxt1
     *
     * @mbggenerated
     */
    public String getSaleBytxt1() {
        return saleBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bytxt1
     *
     * @param saleBytxt1 the value for t_pos_sale_detail.sale_bytxt1
     *
     * @mbggenerated
     */
    public void setSaleBytxt1(String saleBytxt1) {
        this.saleBytxt1 = saleBytxt1 == null ? null : saleBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bytxt2
     *
     * @return the value of t_pos_sale_detail.sale_bytxt2
     *
     * @mbggenerated
     */
    public String getSaleBytxt2() {
        return saleBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bytxt2
     *
     * @param saleBytxt2 the value for t_pos_sale_detail.sale_bytxt2
     *
     * @mbggenerated
     */
    public void setSaleBytxt2(String saleBytxt2) {
        this.saleBytxt2 = saleBytxt2 == null ? null : saleBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bytxt3
     *
     * @return the value of t_pos_sale_detail.sale_bytxt3
     *
     * @mbggenerated
     */
    public String getSaleBytxt3() {
        return saleBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bytxt3
     *
     * @param saleBytxt3 the value for t_pos_sale_detail.sale_bytxt3
     *
     * @mbggenerated
     */
    public void setSaleBytxt3(String saleBytxt3) {
        this.saleBytxt3 = saleBytxt3 == null ? null : saleBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bynum1
     *
     * @return the value of t_pos_sale_detail.sale_bynum1
     *
     * @mbggenerated
     */
    public BigDecimal getSaleBynum1() {
        return saleBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bynum1
     *
     * @param saleBynum1 the value for t_pos_sale_detail.sale_bynum1
     *
     * @mbggenerated
     */
    public void setSaleBynum1(BigDecimal saleBynum1) {
        this.saleBynum1 = saleBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bynum2
     *
     * @return the value of t_pos_sale_detail.sale_bynum2
     *
     * @mbggenerated
     */
    public BigDecimal getSaleBynum2() {
        return saleBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bynum2
     *
     * @param saleBynum2 the value for t_pos_sale_detail.sale_bynum2
     *
     * @mbggenerated
     */
    public void setSaleBynum2(BigDecimal saleBynum2) {
        this.saleBynum2 = saleBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.sale_bynum3
     *
     * @return the value of t_pos_sale_detail.sale_bynum3
     *
     * @mbggenerated
     */
    public BigDecimal getSaleBynum3() {
        return saleBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.sale_bynum3
     *
     * @param saleBynum3 the value for t_pos_sale_detail.sale_bynum3
     *
     * @mbggenerated
     */
    public void setSaleBynum3(BigDecimal saleBynum3) {
        this.saleBynum3 = saleBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.allzk_fore_real_price
     *
     * @return the value of t_pos_sale_detail.allzk_fore_real_price
     *
     * @mbggenerated
     */
    public BigDecimal getAllzkForeRealPrice() {
        return allzkForeRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.allzk_fore_real_price
     *
     * @param allzkForeRealPrice the value for t_pos_sale_detail.allzk_fore_real_price
     *
     * @mbggenerated
     */
    public void setAllzkForeRealPrice(BigDecimal allzkForeRealPrice) {
        this.allzkForeRealPrice = allzkForeRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.allzk_fore_special_type
     *
     * @return the value of t_pos_sale_detail.allzk_fore_special_type
     *
     * @mbggenerated
     */
    public String getAllzkForeSpecialType() {
        return allzkForeSpecialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.allzk_fore_special_type
     *
     * @param allzkForeSpecialType the value for t_pos_sale_detail.allzk_fore_special_type
     *
     * @mbggenerated
     */
    public void setAllzkForeSpecialType(String allzkForeSpecialType) {
        this.allzkForeSpecialType = allzkForeSpecialType == null ? null : allzkForeSpecialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.Manage_ly_rate
     *
     * @return the value of t_pos_sale_detail.Manage_ly_rate
     *
     * @mbggenerated
     */
    public BigDecimal getManageLyRate() {
        return manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.Manage_ly_rate
     *
     * @param manageLyRate the value for t_pos_sale_detail.Manage_ly_rate
     *
     * @mbggenerated
     */
    public void setManageLyRate(BigDecimal manageLyRate) {
        this.manageLyRate = manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.ly_sup_no
     *
     * @return the value of t_pos_sale_detail.ly_sup_no
     *
     * @mbggenerated
     */
    public String getLySupNo() {
        return lySupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.ly_sup_no
     *
     * @param lySupNo the value for t_pos_sale_detail.ly_sup_no
     *
     * @mbggenerated
     */
    public void setLySupNo(String lySupNo) {
        this.lySupNo = lySupNo == null ? null : lySupNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.inside_tax_amt
     *
     * @return the value of t_pos_sale_detail.inside_tax_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTaxAmt() {
        return insideTaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.inside_tax_amt
     *
     * @param insideTaxAmt the value for t_pos_sale_detail.inside_tax_amt
     *
     * @mbggenerated
     */
    public void setInsideTaxAmt(BigDecimal insideTaxAmt) {
        this.insideTaxAmt = insideTaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.is_package
     *
     * @return the value of t_pos_sale_detail.is_package
     *
     * @mbggenerated
     */
    public String getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.is_package
     *
     * @param isPackage the value for t_pos_sale_detail.is_package
     *
     * @mbggenerated
     */
    public void setIsPackage(String isPackage) {
        this.isPackage = isPackage == null ? null : isPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.limit_branch
     *
     * @return the value of t_pos_sale_detail.limit_branch
     *
     * @mbggenerated
     */
    public String getLimitBranch() {
        return limitBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.limit_branch
     *
     * @param limitBranch the value for t_pos_sale_detail.limit_branch
     *
     * @mbggenerated
     */
    public void setLimitBranch(String limitBranch) {
        this.limitBranch = limitBranch == null ? null : limitBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.limit_times
     *
     * @return the value of t_pos_sale_detail.limit_times
     *
     * @mbggenerated
     */
    public String getLimitTimes() {
        return limitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.limit_times
     *
     * @param limitTimes the value for t_pos_sale_detail.limit_times
     *
     * @mbggenerated
     */
    public void setLimitTimes(String limitTimes) {
        this.limitTimes = limitTimes == null ? null : limitTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.limit_date
     *
     * @return the value of t_pos_sale_detail.limit_date
     *
     * @mbggenerated
     */
    public String getLimitDate() {
        return limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.limit_date
     *
     * @param limitDate the value for t_pos_sale_detail.limit_date
     *
     * @mbggenerated
     */
    public void setLimitDate(String limitDate) {
        this.limitDate = limitDate == null ? null : limitDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.valid_begin
     *
     * @return the value of t_pos_sale_detail.valid_begin
     *
     * @mbggenerated
     */
    public Date getValidBegin() {
        return validBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.valid_begin
     *
     * @param validBegin the value for t_pos_sale_detail.valid_begin
     *
     * @mbggenerated
     */
    public void setValidBegin(Date validBegin) {
        this.validBegin = validBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pos_sale_detail.valid_end
     *
     * @return the value of t_pos_sale_detail.valid_end
     *
     * @mbggenerated
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pos_sale_detail.valid_end
     *
     * @param validEnd the value for t_pos_sale_detail.valid_end
     *
     * @mbggenerated
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }
}