package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TSupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_no
     *
     * @mbggenerated
     */
    private String supNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_name
     *
     * @mbggenerated
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.suptype_no
     *
     * @mbggenerated
     */
    private String suptypeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.py_code
     *
     * @mbggenerated
     */
    private String pyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.region_no
     *
     * @mbggenerated
     */
    private String regionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.Manage_type
     *
     * @mbggenerated
     */
    private String manageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_man
     *
     * @mbggenerated
     */
    private String supMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.deal_man
     *
     * @mbggenerated
     */
    private String dealMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_address
     *
     * @mbggenerated
     */
    private String supAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_zip
     *
     * @mbggenerated
     */
    private String supZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_email
     *
     * @mbggenerated
     */
    private String supEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_tel
     *
     * @mbggenerated
     */
    private String supTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_mobil
     *
     * @mbggenerated
     */
    private String supMobil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_fax
     *
     * @mbggenerated
     */
    private String supFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_acct_bank
     *
     * @mbggenerated
     */
    private String supAcctBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_acct_no
     *
     * @mbggenerated
     */
    private String supAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.init_amt
     *
     * @mbggenerated
     */
    private BigDecimal initAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.allow_in
     *
     * @mbggenerated
     */
    private String allowIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.allow_accout
     *
     * @mbggenerated
     */
    private String allowAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.check_flag
     *
     * @mbggenerated
     */
    private String checkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.check_day
     *
     * @mbggenerated
     */
    private BigDecimal checkDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_Dist_status
     *
     * @mbggenerated
     */
    private String supDistStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_Stock_status
     *
     * @mbggenerated
     */
    private String supStockStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_regname
     *
     * @mbggenerated
     */
    private String supEntRegname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Corporate
     *
     * @mbggenerated
     */
    private String supEntCorporate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_address
     *
     * @mbggenerated
     */
    private String supEntAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_money
     *
     * @mbggenerated
     */
    private String supEntMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Valid
     *
     * @mbggenerated
     */
    private Date supEntValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_type
     *
     * @mbggenerated
     */
    private String supEntType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_licence
     *
     * @mbggenerated
     */
    private String supEntLicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Tlicence
     *
     * @mbggenerated
     */
    private String supEntTlicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Plicense
     *
     * @mbggenerated
     */
    private String supEntPlicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Hlicense
     *
     * @mbggenerated
     */
    private String supEntHlicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_deal
     *
     * @mbggenerated
     */
    private String supEntDeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Scope
     *
     * @mbggenerated
     */
    private String supEntScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Industry
     *
     * @mbggenerated
     */
    private String supEntIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_Certification
     *
     * @mbggenerated
     */
    private String supEntCertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_regunit
     *
     * @mbggenerated
     */
    private String supEntRegunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_ent_regdate
     *
     * @mbggenerated
     */
    private Date supEntRegdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_memo
     *
     * @mbggenerated
     */
    private String supMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.lock_user
     *
     * @mbggenerated
     */
    private String lockUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bytxt1
     *
     * @mbggenerated
     */
    private String supBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bytxt2
     *
     * @mbggenerated
     */
    private String supBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bytxt3
     *
     * @mbggenerated
     */
    private String supBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bynum1
     *
     * @mbggenerated
     */
    private BigDecimal supBynum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bynum2
     *
     * @mbggenerated
     */
    private BigDecimal supBynum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_bynum3
     *
     * @mbggenerated
     */
    private BigDecimal supBynum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    private BigDecimal manageLyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.Freight_Payer
     *
     * @mbggenerated
     */
    private String freightPayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_Self_Settle
     *
     * @mbggenerated
     */
    private String supSelfSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_user
     *
     * @mbggenerated
     */
    private String supUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.sup_pwd
     *
     * @mbggenerated
     */
    private String supPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sup_info.wx_openid
     *
     * @mbggenerated
     */
    private String wxOpenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_no
     *
     * @return the value of t_sup_info.sup_no
     *
     * @mbggenerated
     */
    public String getSupNo() {
        return supNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_no
     *
     * @param supNo the value for t_sup_info.sup_no
     *
     * @mbggenerated
     */
    public void setSupNo(String supNo) {
        this.supNo = supNo == null ? null : supNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_name
     *
     * @return the value of t_sup_info.sup_name
     *
     * @mbggenerated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_name
     *
     * @param supName the value for t_sup_info.sup_name
     *
     * @mbggenerated
     */
    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.suptype_no
     *
     * @return the value of t_sup_info.suptype_no
     *
     * @mbggenerated
     */
    public String getSuptypeNo() {
        return suptypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.suptype_no
     *
     * @param suptypeNo the value for t_sup_info.suptype_no
     *
     * @mbggenerated
     */
    public void setSuptypeNo(String suptypeNo) {
        this.suptypeNo = suptypeNo == null ? null : suptypeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.py_code
     *
     * @return the value of t_sup_info.py_code
     *
     * @mbggenerated
     */
    public String getPyCode() {
        return pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.py_code
     *
     * @param pyCode the value for t_sup_info.py_code
     *
     * @mbggenerated
     */
    public void setPyCode(String pyCode) {
        this.pyCode = pyCode == null ? null : pyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.region_no
     *
     * @return the value of t_sup_info.region_no
     *
     * @mbggenerated
     */
    public String getRegionNo() {
        return regionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.region_no
     *
     * @param regionNo the value for t_sup_info.region_no
     *
     * @mbggenerated
     */
    public void setRegionNo(String regionNo) {
        this.regionNo = regionNo == null ? null : regionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.Manage_type
     *
     * @return the value of t_sup_info.Manage_type
     *
     * @mbggenerated
     */
    public String getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.Manage_type
     *
     * @param manageType the value for t_sup_info.Manage_type
     *
     * @mbggenerated
     */
    public void setManageType(String manageType) {
        this.manageType = manageType == null ? null : manageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_man
     *
     * @return the value of t_sup_info.sup_man
     *
     * @mbggenerated
     */
    public String getSupMan() {
        return supMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_man
     *
     * @param supMan the value for t_sup_info.sup_man
     *
     * @mbggenerated
     */
    public void setSupMan(String supMan) {
        this.supMan = supMan == null ? null : supMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.deal_man
     *
     * @return the value of t_sup_info.deal_man
     *
     * @mbggenerated
     */
    public String getDealMan() {
        return dealMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.deal_man
     *
     * @param dealMan the value for t_sup_info.deal_man
     *
     * @mbggenerated
     */
    public void setDealMan(String dealMan) {
        this.dealMan = dealMan == null ? null : dealMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_address
     *
     * @return the value of t_sup_info.sup_address
     *
     * @mbggenerated
     */
    public String getSupAddress() {
        return supAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_address
     *
     * @param supAddress the value for t_sup_info.sup_address
     *
     * @mbggenerated
     */
    public void setSupAddress(String supAddress) {
        this.supAddress = supAddress == null ? null : supAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_zip
     *
     * @return the value of t_sup_info.sup_zip
     *
     * @mbggenerated
     */
    public String getSupZip() {
        return supZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_zip
     *
     * @param supZip the value for t_sup_info.sup_zip
     *
     * @mbggenerated
     */
    public void setSupZip(String supZip) {
        this.supZip = supZip == null ? null : supZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_email
     *
     * @return the value of t_sup_info.sup_email
     *
     * @mbggenerated
     */
    public String getSupEmail() {
        return supEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_email
     *
     * @param supEmail the value for t_sup_info.sup_email
     *
     * @mbggenerated
     */
    public void setSupEmail(String supEmail) {
        this.supEmail = supEmail == null ? null : supEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_tel
     *
     * @return the value of t_sup_info.sup_tel
     *
     * @mbggenerated
     */
    public String getSupTel() {
        return supTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_tel
     *
     * @param supTel the value for t_sup_info.sup_tel
     *
     * @mbggenerated
     */
    public void setSupTel(String supTel) {
        this.supTel = supTel == null ? null : supTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_mobil
     *
     * @return the value of t_sup_info.sup_mobil
     *
     * @mbggenerated
     */
    public String getSupMobil() {
        return supMobil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_mobil
     *
     * @param supMobil the value for t_sup_info.sup_mobil
     *
     * @mbggenerated
     */
    public void setSupMobil(String supMobil) {
        this.supMobil = supMobil == null ? null : supMobil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_fax
     *
     * @return the value of t_sup_info.sup_fax
     *
     * @mbggenerated
     */
    public String getSupFax() {
        return supFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_fax
     *
     * @param supFax the value for t_sup_info.sup_fax
     *
     * @mbggenerated
     */
    public void setSupFax(String supFax) {
        this.supFax = supFax == null ? null : supFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_acct_bank
     *
     * @return the value of t_sup_info.sup_acct_bank
     *
     * @mbggenerated
     */
    public String getSupAcctBank() {
        return supAcctBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_acct_bank
     *
     * @param supAcctBank the value for t_sup_info.sup_acct_bank
     *
     * @mbggenerated
     */
    public void setSupAcctBank(String supAcctBank) {
        this.supAcctBank = supAcctBank == null ? null : supAcctBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_acct_no
     *
     * @return the value of t_sup_info.sup_acct_no
     *
     * @mbggenerated
     */
    public String getSupAcctNo() {
        return supAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_acct_no
     *
     * @param supAcctNo the value for t_sup_info.sup_acct_no
     *
     * @mbggenerated
     */
    public void setSupAcctNo(String supAcctNo) {
        this.supAcctNo = supAcctNo == null ? null : supAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.display_flag
     *
     * @return the value of t_sup_info.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.display_flag
     *
     * @param displayFlag the value for t_sup_info.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.init_amt
     *
     * @return the value of t_sup_info.init_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInitAmt() {
        return initAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.init_amt
     *
     * @param initAmt the value for t_sup_info.init_amt
     *
     * @mbggenerated
     */
    public void setInitAmt(BigDecimal initAmt) {
        this.initAmt = initAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.allow_in
     *
     * @return the value of t_sup_info.allow_in
     *
     * @mbggenerated
     */
    public String getAllowIn() {
        return allowIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.allow_in
     *
     * @param allowIn the value for t_sup_info.allow_in
     *
     * @mbggenerated
     */
    public void setAllowIn(String allowIn) {
        this.allowIn = allowIn == null ? null : allowIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.allow_accout
     *
     * @return the value of t_sup_info.allow_accout
     *
     * @mbggenerated
     */
    public String getAllowAccout() {
        return allowAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.allow_accout
     *
     * @param allowAccout the value for t_sup_info.allow_accout
     *
     * @mbggenerated
     */
    public void setAllowAccout(String allowAccout) {
        this.allowAccout = allowAccout == null ? null : allowAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.check_flag
     *
     * @return the value of t_sup_info.check_flag
     *
     * @mbggenerated
     */
    public String getCheckFlag() {
        return checkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.check_flag
     *
     * @param checkFlag the value for t_sup_info.check_flag
     *
     * @mbggenerated
     */
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag == null ? null : checkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.check_day
     *
     * @return the value of t_sup_info.check_day
     *
     * @mbggenerated
     */
    public BigDecimal getCheckDay() {
        return checkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.check_day
     *
     * @param checkDay the value for t_sup_info.check_day
     *
     * @mbggenerated
     */
    public void setCheckDay(BigDecimal checkDay) {
        this.checkDay = checkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_Dist_status
     *
     * @return the value of t_sup_info.sup_Dist_status
     *
     * @mbggenerated
     */
    public String getSupDistStatus() {
        return supDistStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_Dist_status
     *
     * @param supDistStatus the value for t_sup_info.sup_Dist_status
     *
     * @mbggenerated
     */
    public void setSupDistStatus(String supDistStatus) {
        this.supDistStatus = supDistStatus == null ? null : supDistStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_Stock_status
     *
     * @return the value of t_sup_info.sup_Stock_status
     *
     * @mbggenerated
     */
    public String getSupStockStatus() {
        return supStockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_Stock_status
     *
     * @param supStockStatus the value for t_sup_info.sup_Stock_status
     *
     * @mbggenerated
     */
    public void setSupStockStatus(String supStockStatus) {
        this.supStockStatus = supStockStatus == null ? null : supStockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_regname
     *
     * @return the value of t_sup_info.sup_ent_regname
     *
     * @mbggenerated
     */
    public String getSupEntRegname() {
        return supEntRegname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_regname
     *
     * @param supEntRegname the value for t_sup_info.sup_ent_regname
     *
     * @mbggenerated
     */
    public void setSupEntRegname(String supEntRegname) {
        this.supEntRegname = supEntRegname == null ? null : supEntRegname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Corporate
     *
     * @return the value of t_sup_info.sup_ent_Corporate
     *
     * @mbggenerated
     */
    public String getSupEntCorporate() {
        return supEntCorporate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Corporate
     *
     * @param supEntCorporate the value for t_sup_info.sup_ent_Corporate
     *
     * @mbggenerated
     */
    public void setSupEntCorporate(String supEntCorporate) {
        this.supEntCorporate = supEntCorporate == null ? null : supEntCorporate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_address
     *
     * @return the value of t_sup_info.sup_ent_address
     *
     * @mbggenerated
     */
    public String getSupEntAddress() {
        return supEntAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_address
     *
     * @param supEntAddress the value for t_sup_info.sup_ent_address
     *
     * @mbggenerated
     */
    public void setSupEntAddress(String supEntAddress) {
        this.supEntAddress = supEntAddress == null ? null : supEntAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_money
     *
     * @return the value of t_sup_info.sup_ent_money
     *
     * @mbggenerated
     */
    public String getSupEntMoney() {
        return supEntMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_money
     *
     * @param supEntMoney the value for t_sup_info.sup_ent_money
     *
     * @mbggenerated
     */
    public void setSupEntMoney(String supEntMoney) {
        this.supEntMoney = supEntMoney == null ? null : supEntMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Valid
     *
     * @return the value of t_sup_info.sup_ent_Valid
     *
     * @mbggenerated
     */
    public Date getSupEntValid() {
        return supEntValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Valid
     *
     * @param supEntValid the value for t_sup_info.sup_ent_Valid
     *
     * @mbggenerated
     */
    public void setSupEntValid(Date supEntValid) {
        this.supEntValid = supEntValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_type
     *
     * @return the value of t_sup_info.sup_ent_type
     *
     * @mbggenerated
     */
    public String getSupEntType() {
        return supEntType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_type
     *
     * @param supEntType the value for t_sup_info.sup_ent_type
     *
     * @mbggenerated
     */
    public void setSupEntType(String supEntType) {
        this.supEntType = supEntType == null ? null : supEntType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_licence
     *
     * @return the value of t_sup_info.sup_ent_licence
     *
     * @mbggenerated
     */
    public String getSupEntLicence() {
        return supEntLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_licence
     *
     * @param supEntLicence the value for t_sup_info.sup_ent_licence
     *
     * @mbggenerated
     */
    public void setSupEntLicence(String supEntLicence) {
        this.supEntLicence = supEntLicence == null ? null : supEntLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Tlicence
     *
     * @return the value of t_sup_info.sup_ent_Tlicence
     *
     * @mbggenerated
     */
    public String getSupEntTlicence() {
        return supEntTlicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Tlicence
     *
     * @param supEntTlicence the value for t_sup_info.sup_ent_Tlicence
     *
     * @mbggenerated
     */
    public void setSupEntTlicence(String supEntTlicence) {
        this.supEntTlicence = supEntTlicence == null ? null : supEntTlicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Plicense
     *
     * @return the value of t_sup_info.sup_ent_Plicense
     *
     * @mbggenerated
     */
    public String getSupEntPlicense() {
        return supEntPlicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Plicense
     *
     * @param supEntPlicense the value for t_sup_info.sup_ent_Plicense
     *
     * @mbggenerated
     */
    public void setSupEntPlicense(String supEntPlicense) {
        this.supEntPlicense = supEntPlicense == null ? null : supEntPlicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Hlicense
     *
     * @return the value of t_sup_info.sup_ent_Hlicense
     *
     * @mbggenerated
     */
    public String getSupEntHlicense() {
        return supEntHlicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Hlicense
     *
     * @param supEntHlicense the value for t_sup_info.sup_ent_Hlicense
     *
     * @mbggenerated
     */
    public void setSupEntHlicense(String supEntHlicense) {
        this.supEntHlicense = supEntHlicense == null ? null : supEntHlicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_deal
     *
     * @return the value of t_sup_info.sup_ent_deal
     *
     * @mbggenerated
     */
    public String getSupEntDeal() {
        return supEntDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_deal
     *
     * @param supEntDeal the value for t_sup_info.sup_ent_deal
     *
     * @mbggenerated
     */
    public void setSupEntDeal(String supEntDeal) {
        this.supEntDeal = supEntDeal == null ? null : supEntDeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Scope
     *
     * @return the value of t_sup_info.sup_ent_Scope
     *
     * @mbggenerated
     */
    public String getSupEntScope() {
        return supEntScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Scope
     *
     * @param supEntScope the value for t_sup_info.sup_ent_Scope
     *
     * @mbggenerated
     */
    public void setSupEntScope(String supEntScope) {
        this.supEntScope = supEntScope == null ? null : supEntScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Industry
     *
     * @return the value of t_sup_info.sup_ent_Industry
     *
     * @mbggenerated
     */
    public String getSupEntIndustry() {
        return supEntIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Industry
     *
     * @param supEntIndustry the value for t_sup_info.sup_ent_Industry
     *
     * @mbggenerated
     */
    public void setSupEntIndustry(String supEntIndustry) {
        this.supEntIndustry = supEntIndustry == null ? null : supEntIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_Certification
     *
     * @return the value of t_sup_info.sup_ent_Certification
     *
     * @mbggenerated
     */
    public String getSupEntCertification() {
        return supEntCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_Certification
     *
     * @param supEntCertification the value for t_sup_info.sup_ent_Certification
     *
     * @mbggenerated
     */
    public void setSupEntCertification(String supEntCertification) {
        this.supEntCertification = supEntCertification == null ? null : supEntCertification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_regunit
     *
     * @return the value of t_sup_info.sup_ent_regunit
     *
     * @mbggenerated
     */
    public String getSupEntRegunit() {
        return supEntRegunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_regunit
     *
     * @param supEntRegunit the value for t_sup_info.sup_ent_regunit
     *
     * @mbggenerated
     */
    public void setSupEntRegunit(String supEntRegunit) {
        this.supEntRegunit = supEntRegunit == null ? null : supEntRegunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_ent_regdate
     *
     * @return the value of t_sup_info.sup_ent_regdate
     *
     * @mbggenerated
     */
    public Date getSupEntRegdate() {
        return supEntRegdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_ent_regdate
     *
     * @param supEntRegdate the value for t_sup_info.sup_ent_regdate
     *
     * @mbggenerated
     */
    public void setSupEntRegdate(Date supEntRegdate) {
        this.supEntRegdate = supEntRegdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_memo
     *
     * @return the value of t_sup_info.sup_memo
     *
     * @mbggenerated
     */
    public String getSupMemo() {
        return supMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_memo
     *
     * @param supMemo the value for t_sup_info.sup_memo
     *
     * @mbggenerated
     */
    public void setSupMemo(String supMemo) {
        this.supMemo = supMemo == null ? null : supMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.create_date
     *
     * @return the value of t_sup_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.create_date
     *
     * @param createDate the value for t_sup_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.create_user
     *
     * @return the value of t_sup_info.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.create_user
     *
     * @param createUser the value for t_sup_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.modify_date
     *
     * @return the value of t_sup_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.modify_date
     *
     * @param modifyDate the value for t_sup_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.modify_user
     *
     * @return the value of t_sup_info.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.modify_user
     *
     * @param modifyUser the value for t_sup_info.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.lock_user
     *
     * @return the value of t_sup_info.lock_user
     *
     * @mbggenerated
     */
    public String getLockUser() {
        return lockUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.lock_user
     *
     * @param lockUser the value for t_sup_info.lock_user
     *
     * @mbggenerated
     */
    public void setLockUser(String lockUser) {
        this.lockUser = lockUser == null ? null : lockUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.IsSysFlag
     *
     * @return the value of t_sup_info.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.IsSysFlag
     *
     * @param issysflag the value for t_sup_info.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bytxt1
     *
     * @return the value of t_sup_info.sup_bytxt1
     *
     * @mbggenerated
     */
    public String getSupBytxt1() {
        return supBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bytxt1
     *
     * @param supBytxt1 the value for t_sup_info.sup_bytxt1
     *
     * @mbggenerated
     */
    public void setSupBytxt1(String supBytxt1) {
        this.supBytxt1 = supBytxt1 == null ? null : supBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bytxt2
     *
     * @return the value of t_sup_info.sup_bytxt2
     *
     * @mbggenerated
     */
    public String getSupBytxt2() {
        return supBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bytxt2
     *
     * @param supBytxt2 the value for t_sup_info.sup_bytxt2
     *
     * @mbggenerated
     */
    public void setSupBytxt2(String supBytxt2) {
        this.supBytxt2 = supBytxt2 == null ? null : supBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bytxt3
     *
     * @return the value of t_sup_info.sup_bytxt3
     *
     * @mbggenerated
     */
    public String getSupBytxt3() {
        return supBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bytxt3
     *
     * @param supBytxt3 the value for t_sup_info.sup_bytxt3
     *
     * @mbggenerated
     */
    public void setSupBytxt3(String supBytxt3) {
        this.supBytxt3 = supBytxt3 == null ? null : supBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bynum1
     *
     * @return the value of t_sup_info.sup_bynum1
     *
     * @mbggenerated
     */
    public BigDecimal getSupBynum1() {
        return supBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bynum1
     *
     * @param supBynum1 the value for t_sup_info.sup_bynum1
     *
     * @mbggenerated
     */
    public void setSupBynum1(BigDecimal supBynum1) {
        this.supBynum1 = supBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bynum2
     *
     * @return the value of t_sup_info.sup_bynum2
     *
     * @mbggenerated
     */
    public BigDecimal getSupBynum2() {
        return supBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bynum2
     *
     * @param supBynum2 the value for t_sup_info.sup_bynum2
     *
     * @mbggenerated
     */
    public void setSupBynum2(BigDecimal supBynum2) {
        this.supBynum2 = supBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_bynum3
     *
     * @return the value of t_sup_info.sup_bynum3
     *
     * @mbggenerated
     */
    public BigDecimal getSupBynum3() {
        return supBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_bynum3
     *
     * @param supBynum3 the value for t_sup_info.sup_bynum3
     *
     * @mbggenerated
     */
    public void setSupBynum3(BigDecimal supBynum3) {
        this.supBynum3 = supBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.update_flow
     *
     * @return the value of t_sup_info.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.update_flow
     *
     * @param updateFlow the value for t_sup_info.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.Manage_ly_rate
     *
     * @return the value of t_sup_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    public BigDecimal getManageLyRate() {
        return manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.Manage_ly_rate
     *
     * @param manageLyRate the value for t_sup_info.Manage_ly_rate
     *
     * @mbggenerated
     */
    public void setManageLyRate(BigDecimal manageLyRate) {
        this.manageLyRate = manageLyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.branch_no
     *
     * @return the value of t_sup_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.branch_no
     *
     * @param branchNo the value for t_sup_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.update_time
     *
     * @return the value of t_sup_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.update_time
     *
     * @param updateTime the value for t_sup_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.update_branch
     *
     * @return the value of t_sup_info.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.update_branch
     *
     * @param updateBranch the value for t_sup_info.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.Freight_Payer
     *
     * @return the value of t_sup_info.Freight_Payer
     *
     * @mbggenerated
     */
    public String getFreightPayer() {
        return freightPayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.Freight_Payer
     *
     * @param freightPayer the value for t_sup_info.Freight_Payer
     *
     * @mbggenerated
     */
    public void setFreightPayer(String freightPayer) {
        this.freightPayer = freightPayer == null ? null : freightPayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_Self_Settle
     *
     * @return the value of t_sup_info.sup_Self_Settle
     *
     * @mbggenerated
     */
    public String getSupSelfSettle() {
        return supSelfSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_Self_Settle
     *
     * @param supSelfSettle the value for t_sup_info.sup_Self_Settle
     *
     * @mbggenerated
     */
    public void setSupSelfSettle(String supSelfSettle) {
        this.supSelfSettle = supSelfSettle == null ? null : supSelfSettle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_user
     *
     * @return the value of t_sup_info.sup_user
     *
     * @mbggenerated
     */
    public String getSupUser() {
        return supUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_user
     *
     * @param supUser the value for t_sup_info.sup_user
     *
     * @mbggenerated
     */
    public void setSupUser(String supUser) {
        this.supUser = supUser == null ? null : supUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.sup_pwd
     *
     * @return the value of t_sup_info.sup_pwd
     *
     * @mbggenerated
     */
    public String getSupPwd() {
        return supPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.sup_pwd
     *
     * @param supPwd the value for t_sup_info.sup_pwd
     *
     * @mbggenerated
     */
    public void setSupPwd(String supPwd) {
        this.supPwd = supPwd == null ? null : supPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.trans_upflag
     *
     * @return the value of t_sup_info.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.trans_upflag
     *
     * @param transUpflag the value for t_sup_info.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sup_info.wx_openid
     *
     * @return the value of t_sup_info.wx_openid
     *
     * @mbggenerated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sup_info.wx_openid
     *
     * @param wxOpenid the value for t_sup_info.wx_openid
     *
     * @mbggenerated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }
}