package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.oper_type
     *
     * @mbggenerated
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_pw
     *
     * @mbggenerated
     */
    private String userPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_status
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.cashier_grant
     *
     * @mbggenerated
     */
    private String cashierGrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.min_zk
     *
     * @mbggenerated
     */
    private BigDecimal minZk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.max_gd
     *
     * @mbggenerated
     */
    private Long maxGd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.max_free
     *
     * @mbggenerated
     */
    private BigDecimal maxFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_LoginPos
     *
     * @mbggenerated
     */
    private String userLoginpos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_LoginHT
     *
     * @mbggenerated
     */
    private String userLoginht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_emp_no
     *
     * @mbggenerated
     */
    private String userEmpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_card
     *
     * @mbggenerated
     */
    private String userCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.grant_payment
     *
     * @mbggenerated
     */
    private String grantPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_LoginWEB
     *
     * @mbggenerated
     */
    private String userLoginweb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.wx_openid
     *
     * @mbggenerated
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.wx_grant
     *
     * @mbggenerated
     */
    private String wxGrant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_id
     *
     * @return the value of t_sys_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_id
     *
     * @param userId the value for t_sys_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.oper_type
     *
     * @return the value of t_sys_user.oper_type
     *
     * @mbggenerated
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.oper_type
     *
     * @param operType the value for t_sys_user.oper_type
     *
     * @mbggenerated
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_name
     *
     * @return the value of t_sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_name
     *
     * @param userName the value for t_sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_pw
     *
     * @return the value of t_sys_user.user_pw
     *
     * @mbggenerated
     */
    public String getUserPw() {
        return userPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_pw
     *
     * @param userPw the value for t_sys_user.user_pw
     *
     * @mbggenerated
     */
    public void setUserPw(String userPw) {
        this.userPw = userPw == null ? null : userPw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_status
     *
     * @return the value of t_sys_user.user_status
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_status
     *
     * @param userStatus the value for t_sys_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.cashier_grant
     *
     * @return the value of t_sys_user.cashier_grant
     *
     * @mbggenerated
     */
    public String getCashierGrant() {
        return cashierGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.cashier_grant
     *
     * @param cashierGrant the value for t_sys_user.cashier_grant
     *
     * @mbggenerated
     */
    public void setCashierGrant(String cashierGrant) {
        this.cashierGrant = cashierGrant == null ? null : cashierGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.min_zk
     *
     * @return the value of t_sys_user.min_zk
     *
     * @mbggenerated
     */
    public BigDecimal getMinZk() {
        return minZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.min_zk
     *
     * @param minZk the value for t_sys_user.min_zk
     *
     * @mbggenerated
     */
    public void setMinZk(BigDecimal minZk) {
        this.minZk = minZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.max_gd
     *
     * @return the value of t_sys_user.max_gd
     *
     * @mbggenerated
     */
    public Long getMaxGd() {
        return maxGd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.max_gd
     *
     * @param maxGd the value for t_sys_user.max_gd
     *
     * @mbggenerated
     */
    public void setMaxGd(Long maxGd) {
        this.maxGd = maxGd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.max_free
     *
     * @return the value of t_sys_user.max_free
     *
     * @mbggenerated
     */
    public BigDecimal getMaxFree() {
        return maxFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.max_free
     *
     * @param maxFree the value for t_sys_user.max_free
     *
     * @mbggenerated
     */
    public void setMaxFree(BigDecimal maxFree) {
        this.maxFree = maxFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.update_flow
     *
     * @return the value of t_sys_user.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.update_flow
     *
     * @param updateFlow the value for t_sys_user.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_LoginPos
     *
     * @return the value of t_sys_user.user_LoginPos
     *
     * @mbggenerated
     */
    public String getUserLoginpos() {
        return userLoginpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_LoginPos
     *
     * @param userLoginpos the value for t_sys_user.user_LoginPos
     *
     * @mbggenerated
     */
    public void setUserLoginpos(String userLoginpos) {
        this.userLoginpos = userLoginpos == null ? null : userLoginpos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_LoginHT
     *
     * @return the value of t_sys_user.user_LoginHT
     *
     * @mbggenerated
     */
    public String getUserLoginht() {
        return userLoginht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_LoginHT
     *
     * @param userLoginht the value for t_sys_user.user_LoginHT
     *
     * @mbggenerated
     */
    public void setUserLoginht(String userLoginht) {
        this.userLoginht = userLoginht == null ? null : userLoginht.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_emp_no
     *
     * @return the value of t_sys_user.user_emp_no
     *
     * @mbggenerated
     */
    public String getUserEmpNo() {
        return userEmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_emp_no
     *
     * @param userEmpNo the value for t_sys_user.user_emp_no
     *
     * @mbggenerated
     */
    public void setUserEmpNo(String userEmpNo) {
        this.userEmpNo = userEmpNo == null ? null : userEmpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_card
     *
     * @return the value of t_sys_user.user_card
     *
     * @mbggenerated
     */
    public String getUserCard() {
        return userCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_card
     *
     * @param userCard the value for t_sys_user.user_card
     *
     * @mbggenerated
     */
    public void setUserCard(String userCard) {
        this.userCard = userCard == null ? null : userCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.grant_payment
     *
     * @return the value of t_sys_user.grant_payment
     *
     * @mbggenerated
     */
    public String getGrantPayment() {
        return grantPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.grant_payment
     *
     * @param grantPayment the value for t_sys_user.grant_payment
     *
     * @mbggenerated
     */
    public void setGrantPayment(String grantPayment) {
        this.grantPayment = grantPayment == null ? null : grantPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.branch_no
     *
     * @return the value of t_sys_user.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.branch_no
     *
     * @param branchNo the value for t_sys_user.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_LoginWEB
     *
     * @return the value of t_sys_user.user_LoginWEB
     *
     * @mbggenerated
     */
    public String getUserLoginweb() {
        return userLoginweb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_LoginWEB
     *
     * @param userLoginweb the value for t_sys_user.user_LoginWEB
     *
     * @mbggenerated
     */
    public void setUserLoginweb(String userLoginweb) {
        this.userLoginweb = userLoginweb == null ? null : userLoginweb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.update_time
     *
     * @return the value of t_sys_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.update_time
     *
     * @param updateTime the value for t_sys_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.update_branch
     *
     * @return the value of t_sys_user.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.update_branch
     *
     * @param updateBranch the value for t_sys_user.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.trans_upflag
     *
     * @return the value of t_sys_user.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.trans_upflag
     *
     * @param transUpflag the value for t_sys_user.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.wx_openid
     *
     * @return the value of t_sys_user.wx_openid
     *
     * @mbggenerated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.wx_openid
     *
     * @param wxOpenid the value for t_sys_user.wx_openid
     *
     * @mbggenerated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.wx_grant
     *
     * @return the value of t_sys_user.wx_grant
     *
     * @mbggenerated
     */
    public String getWxGrant() {
        return wxGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.wx_grant
     *
     * @param wxGrant the value for t_sys_user.wx_grant
     *
     * @mbggenerated
     */
    public void setWxGrant(String wxGrant) {
        this.wxGrant = wxGrant == null ? null : wxGrant.trim();
    }
}