package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TVipFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.vip_flow
     *
     * @mbggenerated
     */
    private String vipFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.vip_no
     *
     * @mbggenerated
     */
    private String vipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.vip_dispno
     *
     * @mbggenerated
     */
    private String vipDispno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.work_man
     *
     * @mbggenerated
     */
    private String workMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.oper_user
     *
     * @mbggenerated
     */
    private String operUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.vip_oper_type
     *
     * @mbggenerated
     */
    private String vipOperType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.sales_amt
     *
     * @mbggenerated
     */
    private BigDecimal salesAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.save_amt
     *
     * @mbggenerated
     */
    private BigDecimal saveAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.give_amt
     *
     * @mbggenerated
     */
    private BigDecimal giveAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.ret_amt
     *
     * @mbggenerated
     */
    private BigDecimal retAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.integral
     *
     * @mbggenerated
     */
    private BigDecimal integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.fy_amt
     *
     * @mbggenerated
     */
    private BigDecimal fyAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.payment_no
     *
     * @mbggenerated
     */
    private String paymentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.payment_amt
     *
     * @mbggenerated
     */
    private BigDecimal paymentAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.coin_rate
     *
     * @mbggenerated
     */
    private BigDecimal coinRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.voucher_no
     *
     * @mbggenerated
     */
    private String voucherNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.oper_memo
     *
     * @mbggenerated
     */
    private String operMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bytxt1
     *
     * @mbggenerated
     */
    private String otherBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bytxt2
     *
     * @mbggenerated
     */
    private String otherBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bytxt3
     *
     * @mbggenerated
     */
    private String otherBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bynum1
     *
     * @mbggenerated
     */
    private BigDecimal otherBynum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bynum2
     *
     * @mbggenerated
     */
    private BigDecimal otherBynum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.other_bynum3
     *
     * @mbggenerated
     */
    private BigDecimal otherBynum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.zero_amt
     *
     * @mbggenerated
     */
    private BigDecimal zeroAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_flow.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.vip_flow
     *
     * @return the value of t_vip_flow.vip_flow
     *
     * @mbggenerated
     */
    public String getVipFlow() {
        return vipFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.vip_flow
     *
     * @param vipFlow the value for t_vip_flow.vip_flow
     *
     * @mbggenerated
     */
    public void setVipFlow(String vipFlow) {
        this.vipFlow = vipFlow == null ? null : vipFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.vip_no
     *
     * @return the value of t_vip_flow.vip_no
     *
     * @mbggenerated
     */
    public String getVipNo() {
        return vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.vip_no
     *
     * @param vipNo the value for t_vip_flow.vip_no
     *
     * @mbggenerated
     */
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo == null ? null : vipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.card_no
     *
     * @return the value of t_vip_flow.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.card_no
     *
     * @param cardNo the value for t_vip_flow.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.vip_dispno
     *
     * @return the value of t_vip_flow.vip_dispno
     *
     * @mbggenerated
     */
    public String getVipDispno() {
        return vipDispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.vip_dispno
     *
     * @param vipDispno the value for t_vip_flow.vip_dispno
     *
     * @mbggenerated
     */
    public void setVipDispno(String vipDispno) {
        this.vipDispno = vipDispno == null ? null : vipDispno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.work_man
     *
     * @return the value of t_vip_flow.work_man
     *
     * @mbggenerated
     */
    public String getWorkMan() {
        return workMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.work_man
     *
     * @param workMan the value for t_vip_flow.work_man
     *
     * @mbggenerated
     */
    public void setWorkMan(String workMan) {
        this.workMan = workMan == null ? null : workMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.oper_date
     *
     * @return the value of t_vip_flow.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.oper_date
     *
     * @param operDate the value for t_vip_flow.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.oper_user
     *
     * @return the value of t_vip_flow.oper_user
     *
     * @mbggenerated
     */
    public String getOperUser() {
        return operUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.oper_user
     *
     * @param operUser the value for t_vip_flow.oper_user
     *
     * @mbggenerated
     */
    public void setOperUser(String operUser) {
        this.operUser = operUser == null ? null : operUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.branch_no
     *
     * @return the value of t_vip_flow.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.branch_no
     *
     * @param branchNo the value for t_vip_flow.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.vip_oper_type
     *
     * @return the value of t_vip_flow.vip_oper_type
     *
     * @mbggenerated
     */
    public String getVipOperType() {
        return vipOperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.vip_oper_type
     *
     * @param vipOperType the value for t_vip_flow.vip_oper_type
     *
     * @mbggenerated
     */
    public void setVipOperType(String vipOperType) {
        this.vipOperType = vipOperType == null ? null : vipOperType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.sales_amt
     *
     * @return the value of t_vip_flow.sales_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSalesAmt() {
        return salesAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.sales_amt
     *
     * @param salesAmt the value for t_vip_flow.sales_amt
     *
     * @mbggenerated
     */
    public void setSalesAmt(BigDecimal salesAmt) {
        this.salesAmt = salesAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.save_amt
     *
     * @return the value of t_vip_flow.save_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSaveAmt() {
        return saveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.save_amt
     *
     * @param saveAmt the value for t_vip_flow.save_amt
     *
     * @mbggenerated
     */
    public void setSaveAmt(BigDecimal saveAmt) {
        this.saveAmt = saveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.give_amt
     *
     * @return the value of t_vip_flow.give_amt
     *
     * @mbggenerated
     */
    public BigDecimal getGiveAmt() {
        return giveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.give_amt
     *
     * @param giveAmt the value for t_vip_flow.give_amt
     *
     * @mbggenerated
     */
    public void setGiveAmt(BigDecimal giveAmt) {
        this.giveAmt = giveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.ret_amt
     *
     * @return the value of t_vip_flow.ret_amt
     *
     * @mbggenerated
     */
    public BigDecimal getRetAmt() {
        return retAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.ret_amt
     *
     * @param retAmt the value for t_vip_flow.ret_amt
     *
     * @mbggenerated
     */
    public void setRetAmt(BigDecimal retAmt) {
        this.retAmt = retAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.integral
     *
     * @return the value of t_vip_flow.integral
     *
     * @mbggenerated
     */
    public BigDecimal getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.integral
     *
     * @param integral the value for t_vip_flow.integral
     *
     * @mbggenerated
     */
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.fy_amt
     *
     * @return the value of t_vip_flow.fy_amt
     *
     * @mbggenerated
     */
    public BigDecimal getFyAmt() {
        return fyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.fy_amt
     *
     * @param fyAmt the value for t_vip_flow.fy_amt
     *
     * @mbggenerated
     */
    public void setFyAmt(BigDecimal fyAmt) {
        this.fyAmt = fyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.payment_no
     *
     * @return the value of t_vip_flow.payment_no
     *
     * @mbggenerated
     */
    public String getPaymentNo() {
        return paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.payment_no
     *
     * @param paymentNo the value for t_vip_flow.payment_no
     *
     * @mbggenerated
     */
    public void setPaymentNo(String paymentNo) {
        this.paymentNo = paymentNo == null ? null : paymentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.payment_amt
     *
     * @return the value of t_vip_flow.payment_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPaymentAmt() {
        return paymentAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.payment_amt
     *
     * @param paymentAmt the value for t_vip_flow.payment_amt
     *
     * @mbggenerated
     */
    public void setPaymentAmt(BigDecimal paymentAmt) {
        this.paymentAmt = paymentAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.coin_rate
     *
     * @return the value of t_vip_flow.coin_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCoinRate() {
        return coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.coin_rate
     *
     * @param coinRate the value for t_vip_flow.coin_rate
     *
     * @mbggenerated
     */
    public void setCoinRate(BigDecimal coinRate) {
        this.coinRate = coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.voucher_no
     *
     * @return the value of t_vip_flow.voucher_no
     *
     * @mbggenerated
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.voucher_no
     *
     * @param voucherNo the value for t_vip_flow.voucher_no
     *
     * @mbggenerated
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo == null ? null : voucherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.oper_memo
     *
     * @return the value of t_vip_flow.oper_memo
     *
     * @mbggenerated
     */
    public String getOperMemo() {
        return operMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.oper_memo
     *
     * @param operMemo the value for t_vip_flow.oper_memo
     *
     * @mbggenerated
     */
    public void setOperMemo(String operMemo) {
        this.operMemo = operMemo == null ? null : operMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bytxt1
     *
     * @return the value of t_vip_flow.other_bytxt1
     *
     * @mbggenerated
     */
    public String getOtherBytxt1() {
        return otherBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bytxt1
     *
     * @param otherBytxt1 the value for t_vip_flow.other_bytxt1
     *
     * @mbggenerated
     */
    public void setOtherBytxt1(String otherBytxt1) {
        this.otherBytxt1 = otherBytxt1 == null ? null : otherBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bytxt2
     *
     * @return the value of t_vip_flow.other_bytxt2
     *
     * @mbggenerated
     */
    public String getOtherBytxt2() {
        return otherBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bytxt2
     *
     * @param otherBytxt2 the value for t_vip_flow.other_bytxt2
     *
     * @mbggenerated
     */
    public void setOtherBytxt2(String otherBytxt2) {
        this.otherBytxt2 = otherBytxt2 == null ? null : otherBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bytxt3
     *
     * @return the value of t_vip_flow.other_bytxt3
     *
     * @mbggenerated
     */
    public String getOtherBytxt3() {
        return otherBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bytxt3
     *
     * @param otherBytxt3 the value for t_vip_flow.other_bytxt3
     *
     * @mbggenerated
     */
    public void setOtherBytxt3(String otherBytxt3) {
        this.otherBytxt3 = otherBytxt3 == null ? null : otherBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bynum1
     *
     * @return the value of t_vip_flow.other_bynum1
     *
     * @mbggenerated
     */
    public BigDecimal getOtherBynum1() {
        return otherBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bynum1
     *
     * @param otherBynum1 the value for t_vip_flow.other_bynum1
     *
     * @mbggenerated
     */
    public void setOtherBynum1(BigDecimal otherBynum1) {
        this.otherBynum1 = otherBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bynum2
     *
     * @return the value of t_vip_flow.other_bynum2
     *
     * @mbggenerated
     */
    public BigDecimal getOtherBynum2() {
        return otherBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bynum2
     *
     * @param otherBynum2 the value for t_vip_flow.other_bynum2
     *
     * @mbggenerated
     */
    public void setOtherBynum2(BigDecimal otherBynum2) {
        this.otherBynum2 = otherBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.other_bynum3
     *
     * @return the value of t_vip_flow.other_bynum3
     *
     * @mbggenerated
     */
    public BigDecimal getOtherBynum3() {
        return otherBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.other_bynum3
     *
     * @param otherBynum3 the value for t_vip_flow.other_bynum3
     *
     * @mbggenerated
     */
    public void setOtherBynum3(BigDecimal otherBynum3) {
        this.otherBynum3 = otherBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.zero_amt
     *
     * @return the value of t_vip_flow.zero_amt
     *
     * @mbggenerated
     */
    public BigDecimal getZeroAmt() {
        return zeroAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.zero_amt
     *
     * @param zeroAmt the value for t_vip_flow.zero_amt
     *
     * @mbggenerated
     */
    public void setZeroAmt(BigDecimal zeroAmt) {
        this.zeroAmt = zeroAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.update_flow
     *
     * @return the value of t_vip_flow.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.update_flow
     *
     * @param updateFlow the value for t_vip_flow.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.update_time
     *
     * @return the value of t_vip_flow.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.update_time
     *
     * @param updateTime the value for t_vip_flow.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.update_branch
     *
     * @return the value of t_vip_flow.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.update_branch
     *
     * @param updateBranch the value for t_vip_flow.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_flow.trans_upflag
     *
     * @return the value of t_vip_flow.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_flow.trans_upflag
     *
     * @param transUpflag the value for t_vip_flow.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }
}