package com.gd.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TVipInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_no
     *
     * @mbggenerated
     */
    private String vipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_dispno
     *
     * @mbggenerated
     */
    private String vipDispno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.viptype_no
     *
     * @mbggenerated
     */
    private String viptypeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_attribute_no
     *
     * @mbggenerated
     */
    private String vipAttributeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_name
     *
     * @mbggenerated
     */
    private String vipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_pycode
     *
     * @mbggenerated
     */
    private String vipPycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_sex
     *
     * @mbggenerated
     */
    private String vipSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_address
     *
     * @mbggenerated
     */
    private String vipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_zip
     *
     * @mbggenerated
     */
    private String vipZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_tel
     *
     * @mbggenerated
     */
    private String vipTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_mobil1
     *
     * @mbggenerated
     */
    private String vipMobil1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_mobil2
     *
     * @mbggenerated
     */
    private String vipMobil2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_fax
     *
     * @mbggenerated
     */
    private String vipFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_ID
     *
     * @mbggenerated
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_email
     *
     * @mbggenerated
     */
    private String vipEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_birth_flag
     *
     * @mbggenerated
     */
    private String vipBirthFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_in_date
     *
     * @mbggenerated
     */
    private Date vipInDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_pwd
     *
     * @mbggenerated
     */
    private String vipPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_status
     *
     * @mbggenerated
     */
    private String vipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.ctrl_valid
     *
     * @mbggenerated
     */
    private String ctrlValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    private Date vipStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    private Date vipEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.init_total_amt
     *
     * @mbggenerated
     */
    private BigDecimal initTotalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.init_integral
     *
     * @mbggenerated
     */
    private BigDecimal initIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_credit_amt
     *
     * @mbggenerated
     */
    private BigDecimal vipCreditAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_IsUpgrade
     *
     * @mbggenerated
     */
    private String vipIsupgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.intro_vip_no
     *
     * @mbggenerated
     */
    private String introVipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_adviser_man
     *
     * @mbggenerated
     */
    private String vipAdviserMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_memo
     *
     * @mbggenerated
     */
    private String vipMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_like_memo
     *
     * @mbggenerated
     */
    private String vipLikeMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_dislike_memo
     *
     * @mbggenerated
     */
    private String vipDislikeMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.IsSysFlag
     *
     * @mbggenerated
     */
    private String issysflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_create_man
     *
     * @mbggenerated
     */
    private String vipCreateMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_create_date
     *
     * @mbggenerated
     */
    private Date vipCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bytxt1
     *
     * @mbggenerated
     */
    private String vipBytxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bytxt2
     *
     * @mbggenerated
     */
    private String vipBytxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bytxt3
     *
     * @mbggenerated
     */
    private String vipBytxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bynum1
     *
     * @mbggenerated
     */
    private BigDecimal vipBynum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bynum2
     *
     * @mbggenerated
     */
    private BigDecimal vipBynum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_bynum3
     *
     * @mbggenerated
     */
    private BigDecimal vipBynum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.lock_user
     *
     * @mbggenerated
     */
    private String lockUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_have_pwd
     *
     * @mbggenerated
     */
    private String vipHavePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.update_flow
     *
     * @mbggenerated
     */
    private Long updateFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.init_balance_amt
     *
     * @mbggenerated
     */
    private BigDecimal initBalanceAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_qq
     *
     * @mbggenerated
     */
    private String vipQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_birth_year
     *
     * @mbggenerated
     */
    private Integer vipBirthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_birth_month
     *
     * @mbggenerated
     */
    private Integer vipBirthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_birth_day
     *
     * @mbggenerated
     */
    private Integer vipBirthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_IsLimit
     *
     * @mbggenerated
     */
    private String vipIslimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baby1_name
     *
     * @mbggenerated
     */
    private String baby1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baby1_birth_flag
     *
     * @mbggenerated
     */
    private String baby1BirthFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baby1_birth_year
     *
     * @mbggenerated
     */
    private Integer baby1BirthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baby1_birth_month
     *
     * @mbggenerated
     */
    private Integer baby1BirthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baby1_birth_day
     *
     * @mbggenerated
     */
    private Integer baby1BirthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.update_branch
     *
     * @mbggenerated
     */
    private String updateBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.recom_vip_no
     *
     * @mbggenerated
     */
    private String recomVipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_not_sms
     *
     * @mbggenerated
     */
    private String vipNotSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.baoxian_yx_date
     *
     * @mbggenerated
     */
    private Date baoxianYxDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.nianjian_yx_date
     *
     * @mbggenerated
     */
    private Date nianjianYxDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.vip_web_pwd
     *
     * @mbggenerated
     */
    private String vipWebPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.trans_upflag
     *
     * @mbggenerated
     */
    private String transUpflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_info.wx_openid
     *
     * @mbggenerated
     */
    private String wxOpenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_no
     *
     * @return the value of t_vip_info.vip_no
     *
     * @mbggenerated
     */
    public String getVipNo() {
        return vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_no
     *
     * @param vipNo the value for t_vip_info.vip_no
     *
     * @mbggenerated
     */
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo == null ? null : vipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_dispno
     *
     * @return the value of t_vip_info.vip_dispno
     *
     * @mbggenerated
     */
    public String getVipDispno() {
        return vipDispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_dispno
     *
     * @param vipDispno the value for t_vip_info.vip_dispno
     *
     * @mbggenerated
     */
    public void setVipDispno(String vipDispno) {
        this.vipDispno = vipDispno == null ? null : vipDispno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.viptype_no
     *
     * @return the value of t_vip_info.viptype_no
     *
     * @mbggenerated
     */
    public String getViptypeNo() {
        return viptypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.viptype_no
     *
     * @param viptypeNo the value for t_vip_info.viptype_no
     *
     * @mbggenerated
     */
    public void setViptypeNo(String viptypeNo) {
        this.viptypeNo = viptypeNo == null ? null : viptypeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_attribute_no
     *
     * @return the value of t_vip_info.vip_attribute_no
     *
     * @mbggenerated
     */
    public String getVipAttributeNo() {
        return vipAttributeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_attribute_no
     *
     * @param vipAttributeNo the value for t_vip_info.vip_attribute_no
     *
     * @mbggenerated
     */
    public void setVipAttributeNo(String vipAttributeNo) {
        this.vipAttributeNo = vipAttributeNo == null ? null : vipAttributeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.card_no
     *
     * @return the value of t_vip_info.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.card_no
     *
     * @param cardNo the value for t_vip_info.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.card_type
     *
     * @return the value of t_vip_info.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.card_type
     *
     * @param cardType the value for t_vip_info.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_name
     *
     * @return the value of t_vip_info.vip_name
     *
     * @mbggenerated
     */
    public String getVipName() {
        return vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_name
     *
     * @param vipName the value for t_vip_info.vip_name
     *
     * @mbggenerated
     */
    public void setVipName(String vipName) {
        this.vipName = vipName == null ? null : vipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_pycode
     *
     * @return the value of t_vip_info.vip_pycode
     *
     * @mbggenerated
     */
    public String getVipPycode() {
        return vipPycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_pycode
     *
     * @param vipPycode the value for t_vip_info.vip_pycode
     *
     * @mbggenerated
     */
    public void setVipPycode(String vipPycode) {
        this.vipPycode = vipPycode == null ? null : vipPycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_sex
     *
     * @return the value of t_vip_info.vip_sex
     *
     * @mbggenerated
     */
    public String getVipSex() {
        return vipSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_sex
     *
     * @param vipSex the value for t_vip_info.vip_sex
     *
     * @mbggenerated
     */
    public void setVipSex(String vipSex) {
        this.vipSex = vipSex == null ? null : vipSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_address
     *
     * @return the value of t_vip_info.vip_address
     *
     * @mbggenerated
     */
    public String getVipAddress() {
        return vipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_address
     *
     * @param vipAddress the value for t_vip_info.vip_address
     *
     * @mbggenerated
     */
    public void setVipAddress(String vipAddress) {
        this.vipAddress = vipAddress == null ? null : vipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_zip
     *
     * @return the value of t_vip_info.vip_zip
     *
     * @mbggenerated
     */
    public String getVipZip() {
        return vipZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_zip
     *
     * @param vipZip the value for t_vip_info.vip_zip
     *
     * @mbggenerated
     */
    public void setVipZip(String vipZip) {
        this.vipZip = vipZip == null ? null : vipZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_tel
     *
     * @return the value of t_vip_info.vip_tel
     *
     * @mbggenerated
     */
    public String getVipTel() {
        return vipTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_tel
     *
     * @param vipTel the value for t_vip_info.vip_tel
     *
     * @mbggenerated
     */
    public void setVipTel(String vipTel) {
        this.vipTel = vipTel == null ? null : vipTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_mobil1
     *
     * @return the value of t_vip_info.vip_mobil1
     *
     * @mbggenerated
     */
    public String getVipMobil1() {
        return vipMobil1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_mobil1
     *
     * @param vipMobil1 the value for t_vip_info.vip_mobil1
     *
     * @mbggenerated
     */
    public void setVipMobil1(String vipMobil1) {
        this.vipMobil1 = vipMobil1 == null ? null : vipMobil1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_mobil2
     *
     * @return the value of t_vip_info.vip_mobil2
     *
     * @mbggenerated
     */
    public String getVipMobil2() {
        return vipMobil2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_mobil2
     *
     * @param vipMobil2 the value for t_vip_info.vip_mobil2
     *
     * @mbggenerated
     */
    public void setVipMobil2(String vipMobil2) {
        this.vipMobil2 = vipMobil2 == null ? null : vipMobil2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_fax
     *
     * @return the value of t_vip_info.vip_fax
     *
     * @mbggenerated
     */
    public String getVipFax() {
        return vipFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_fax
     *
     * @param vipFax the value for t_vip_info.vip_fax
     *
     * @mbggenerated
     */
    public void setVipFax(String vipFax) {
        this.vipFax = vipFax == null ? null : vipFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_ID
     *
     * @return the value of t_vip_info.vip_ID
     *
     * @mbggenerated
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_ID
     *
     * @param vipId the value for t_vip_info.vip_ID
     *
     * @mbggenerated
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_email
     *
     * @return the value of t_vip_info.vip_email
     *
     * @mbggenerated
     */
    public String getVipEmail() {
        return vipEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_email
     *
     * @param vipEmail the value for t_vip_info.vip_email
     *
     * @mbggenerated
     */
    public void setVipEmail(String vipEmail) {
        this.vipEmail = vipEmail == null ? null : vipEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_birth_flag
     *
     * @return the value of t_vip_info.vip_birth_flag
     *
     * @mbggenerated
     */
    public String getVipBirthFlag() {
        return vipBirthFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_birth_flag
     *
     * @param vipBirthFlag the value for t_vip_info.vip_birth_flag
     *
     * @mbggenerated
     */
    public void setVipBirthFlag(String vipBirthFlag) {
        this.vipBirthFlag = vipBirthFlag == null ? null : vipBirthFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_in_date
     *
     * @return the value of t_vip_info.vip_in_date
     *
     * @mbggenerated
     */
    public Date getVipInDate() {
        return vipInDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_in_date
     *
     * @param vipInDate the value for t_vip_info.vip_in_date
     *
     * @mbggenerated
     */
    public void setVipInDate(Date vipInDate) {
        this.vipInDate = vipInDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_pwd
     *
     * @return the value of t_vip_info.vip_pwd
     *
     * @mbggenerated
     */
    public String getVipPwd() {
        return vipPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_pwd
     *
     * @param vipPwd the value for t_vip_info.vip_pwd
     *
     * @mbggenerated
     */
    public void setVipPwd(String vipPwd) {
        this.vipPwd = vipPwd == null ? null : vipPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_status
     *
     * @return the value of t_vip_info.vip_status
     *
     * @mbggenerated
     */
    public String getVipStatus() {
        return vipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_status
     *
     * @param vipStatus the value for t_vip_info.vip_status
     *
     * @mbggenerated
     */
    public void setVipStatus(String vipStatus) {
        this.vipStatus = vipStatus == null ? null : vipStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.ctrl_valid
     *
     * @return the value of t_vip_info.ctrl_valid
     *
     * @mbggenerated
     */
    public String getCtrlValid() {
        return ctrlValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.ctrl_valid
     *
     * @param ctrlValid the value for t_vip_info.ctrl_valid
     *
     * @mbggenerated
     */
    public void setCtrlValid(String ctrlValid) {
        this.ctrlValid = ctrlValid == null ? null : ctrlValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_start_date
     *
     * @return the value of t_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    public Date getVipStartDate() {
        return vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_start_date
     *
     * @param vipStartDate the value for t_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    public void setVipStartDate(Date vipStartDate) {
        this.vipStartDate = vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_end_date
     *
     * @return the value of t_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    public Date getVipEndDate() {
        return vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_end_date
     *
     * @param vipEndDate the value for t_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    public void setVipEndDate(Date vipEndDate) {
        this.vipEndDate = vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.init_total_amt
     *
     * @return the value of t_vip_info.init_total_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInitTotalAmt() {
        return initTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.init_total_amt
     *
     * @param initTotalAmt the value for t_vip_info.init_total_amt
     *
     * @mbggenerated
     */
    public void setInitTotalAmt(BigDecimal initTotalAmt) {
        this.initTotalAmt = initTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.init_integral
     *
     * @return the value of t_vip_info.init_integral
     *
     * @mbggenerated
     */
    public BigDecimal getInitIntegral() {
        return initIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.init_integral
     *
     * @param initIntegral the value for t_vip_info.init_integral
     *
     * @mbggenerated
     */
    public void setInitIntegral(BigDecimal initIntegral) {
        this.initIntegral = initIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_credit_amt
     *
     * @return the value of t_vip_info.vip_credit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getVipCreditAmt() {
        return vipCreditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_credit_amt
     *
     * @param vipCreditAmt the value for t_vip_info.vip_credit_amt
     *
     * @mbggenerated
     */
    public void setVipCreditAmt(BigDecimal vipCreditAmt) {
        this.vipCreditAmt = vipCreditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_IsUpgrade
     *
     * @return the value of t_vip_info.vip_IsUpgrade
     *
     * @mbggenerated
     */
    public String getVipIsupgrade() {
        return vipIsupgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_IsUpgrade
     *
     * @param vipIsupgrade the value for t_vip_info.vip_IsUpgrade
     *
     * @mbggenerated
     */
    public void setVipIsupgrade(String vipIsupgrade) {
        this.vipIsupgrade = vipIsupgrade == null ? null : vipIsupgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.intro_vip_no
     *
     * @return the value of t_vip_info.intro_vip_no
     *
     * @mbggenerated
     */
    public String getIntroVipNo() {
        return introVipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.intro_vip_no
     *
     * @param introVipNo the value for t_vip_info.intro_vip_no
     *
     * @mbggenerated
     */
    public void setIntroVipNo(String introVipNo) {
        this.introVipNo = introVipNo == null ? null : introVipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_adviser_man
     *
     * @return the value of t_vip_info.vip_adviser_man
     *
     * @mbggenerated
     */
    public String getVipAdviserMan() {
        return vipAdviserMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_adviser_man
     *
     * @param vipAdviserMan the value for t_vip_info.vip_adviser_man
     *
     * @mbggenerated
     */
    public void setVipAdviserMan(String vipAdviserMan) {
        this.vipAdviserMan = vipAdviserMan == null ? null : vipAdviserMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_memo
     *
     * @return the value of t_vip_info.vip_memo
     *
     * @mbggenerated
     */
    public String getVipMemo() {
        return vipMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_memo
     *
     * @param vipMemo the value for t_vip_info.vip_memo
     *
     * @mbggenerated
     */
    public void setVipMemo(String vipMemo) {
        this.vipMemo = vipMemo == null ? null : vipMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_like_memo
     *
     * @return the value of t_vip_info.vip_like_memo
     *
     * @mbggenerated
     */
    public String getVipLikeMemo() {
        return vipLikeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_like_memo
     *
     * @param vipLikeMemo the value for t_vip_info.vip_like_memo
     *
     * @mbggenerated
     */
    public void setVipLikeMemo(String vipLikeMemo) {
        this.vipLikeMemo = vipLikeMemo == null ? null : vipLikeMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_dislike_memo
     *
     * @return the value of t_vip_info.vip_dislike_memo
     *
     * @mbggenerated
     */
    public String getVipDislikeMemo() {
        return vipDislikeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_dislike_memo
     *
     * @param vipDislikeMemo the value for t_vip_info.vip_dislike_memo
     *
     * @mbggenerated
     */
    public void setVipDislikeMemo(String vipDislikeMemo) {
        this.vipDislikeMemo = vipDislikeMemo == null ? null : vipDislikeMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.IsSysFlag
     *
     * @return the value of t_vip_info.IsSysFlag
     *
     * @mbggenerated
     */
    public String getIssysflag() {
        return issysflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.IsSysFlag
     *
     * @param issysflag the value for t_vip_info.IsSysFlag
     *
     * @mbggenerated
     */
    public void setIssysflag(String issysflag) {
        this.issysflag = issysflag == null ? null : issysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.create_user
     *
     * @return the value of t_vip_info.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.create_user
     *
     * @param createUser the value for t_vip_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.create_date
     *
     * @return the value of t_vip_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.create_date
     *
     * @param createDate the value for t_vip_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_create_man
     *
     * @return the value of t_vip_info.vip_create_man
     *
     * @mbggenerated
     */
    public String getVipCreateMan() {
        return vipCreateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_create_man
     *
     * @param vipCreateMan the value for t_vip_info.vip_create_man
     *
     * @mbggenerated
     */
    public void setVipCreateMan(String vipCreateMan) {
        this.vipCreateMan = vipCreateMan == null ? null : vipCreateMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_create_date
     *
     * @return the value of t_vip_info.vip_create_date
     *
     * @mbggenerated
     */
    public Date getVipCreateDate() {
        return vipCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_create_date
     *
     * @param vipCreateDate the value for t_vip_info.vip_create_date
     *
     * @mbggenerated
     */
    public void setVipCreateDate(Date vipCreateDate) {
        this.vipCreateDate = vipCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.modify_user
     *
     * @return the value of t_vip_info.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.modify_user
     *
     * @param modifyUser the value for t_vip_info.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.modify_date
     *
     * @return the value of t_vip_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.modify_date
     *
     * @param modifyDate the value for t_vip_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bytxt1
     *
     * @return the value of t_vip_info.vip_bytxt1
     *
     * @mbggenerated
     */
    public String getVipBytxt1() {
        return vipBytxt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bytxt1
     *
     * @param vipBytxt1 the value for t_vip_info.vip_bytxt1
     *
     * @mbggenerated
     */
    public void setVipBytxt1(String vipBytxt1) {
        this.vipBytxt1 = vipBytxt1 == null ? null : vipBytxt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bytxt2
     *
     * @return the value of t_vip_info.vip_bytxt2
     *
     * @mbggenerated
     */
    public String getVipBytxt2() {
        return vipBytxt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bytxt2
     *
     * @param vipBytxt2 the value for t_vip_info.vip_bytxt2
     *
     * @mbggenerated
     */
    public void setVipBytxt2(String vipBytxt2) {
        this.vipBytxt2 = vipBytxt2 == null ? null : vipBytxt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bytxt3
     *
     * @return the value of t_vip_info.vip_bytxt3
     *
     * @mbggenerated
     */
    public String getVipBytxt3() {
        return vipBytxt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bytxt3
     *
     * @param vipBytxt3 the value for t_vip_info.vip_bytxt3
     *
     * @mbggenerated
     */
    public void setVipBytxt3(String vipBytxt3) {
        this.vipBytxt3 = vipBytxt3 == null ? null : vipBytxt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bynum1
     *
     * @return the value of t_vip_info.vip_bynum1
     *
     * @mbggenerated
     */
    public BigDecimal getVipBynum1() {
        return vipBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bynum1
     *
     * @param vipBynum1 the value for t_vip_info.vip_bynum1
     *
     * @mbggenerated
     */
    public void setVipBynum1(BigDecimal vipBynum1) {
        this.vipBynum1 = vipBynum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bynum2
     *
     * @return the value of t_vip_info.vip_bynum2
     *
     * @mbggenerated
     */
    public BigDecimal getVipBynum2() {
        return vipBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bynum2
     *
     * @param vipBynum2 the value for t_vip_info.vip_bynum2
     *
     * @mbggenerated
     */
    public void setVipBynum2(BigDecimal vipBynum2) {
        this.vipBynum2 = vipBynum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_bynum3
     *
     * @return the value of t_vip_info.vip_bynum3
     *
     * @mbggenerated
     */
    public BigDecimal getVipBynum3() {
        return vipBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_bynum3
     *
     * @param vipBynum3 the value for t_vip_info.vip_bynum3
     *
     * @mbggenerated
     */
    public void setVipBynum3(BigDecimal vipBynum3) {
        this.vipBynum3 = vipBynum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.lock_user
     *
     * @return the value of t_vip_info.lock_user
     *
     * @mbggenerated
     */
    public String getLockUser() {
        return lockUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.lock_user
     *
     * @param lockUser the value for t_vip_info.lock_user
     *
     * @mbggenerated
     */
    public void setLockUser(String lockUser) {
        this.lockUser = lockUser == null ? null : lockUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.branch_no
     *
     * @return the value of t_vip_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.branch_no
     *
     * @param branchNo the value for t_vip_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_have_pwd
     *
     * @return the value of t_vip_info.vip_have_pwd
     *
     * @mbggenerated
     */
    public String getVipHavePwd() {
        return vipHavePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_have_pwd
     *
     * @param vipHavePwd the value for t_vip_info.vip_have_pwd
     *
     * @mbggenerated
     */
    public void setVipHavePwd(String vipHavePwd) {
        this.vipHavePwd = vipHavePwd == null ? null : vipHavePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.update_flow
     *
     * @return the value of t_vip_info.update_flow
     *
     * @mbggenerated
     */
    public Long getUpdateFlow() {
        return updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.update_flow
     *
     * @param updateFlow the value for t_vip_info.update_flow
     *
     * @mbggenerated
     */
    public void setUpdateFlow(Long updateFlow) {
        this.updateFlow = updateFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.init_balance_amt
     *
     * @return the value of t_vip_info.init_balance_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInitBalanceAmt() {
        return initBalanceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.init_balance_amt
     *
     * @param initBalanceAmt the value for t_vip_info.init_balance_amt
     *
     * @mbggenerated
     */
    public void setInitBalanceAmt(BigDecimal initBalanceAmt) {
        this.initBalanceAmt = initBalanceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_qq
     *
     * @return the value of t_vip_info.vip_qq
     *
     * @mbggenerated
     */
    public String getVipQq() {
        return vipQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_qq
     *
     * @param vipQq the value for t_vip_info.vip_qq
     *
     * @mbggenerated
     */
    public void setVipQq(String vipQq) {
        this.vipQq = vipQq == null ? null : vipQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_birth_year
     *
     * @return the value of t_vip_info.vip_birth_year
     *
     * @mbggenerated
     */
    public Integer getVipBirthYear() {
        return vipBirthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_birth_year
     *
     * @param vipBirthYear the value for t_vip_info.vip_birth_year
     *
     * @mbggenerated
     */
    public void setVipBirthYear(Integer vipBirthYear) {
        this.vipBirthYear = vipBirthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_birth_month
     *
     * @return the value of t_vip_info.vip_birth_month
     *
     * @mbggenerated
     */
    public Integer getVipBirthMonth() {
        return vipBirthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_birth_month
     *
     * @param vipBirthMonth the value for t_vip_info.vip_birth_month
     *
     * @mbggenerated
     */
    public void setVipBirthMonth(Integer vipBirthMonth) {
        this.vipBirthMonth = vipBirthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_birth_day
     *
     * @return the value of t_vip_info.vip_birth_day
     *
     * @mbggenerated
     */
    public Integer getVipBirthDay() {
        return vipBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_birth_day
     *
     * @param vipBirthDay the value for t_vip_info.vip_birth_day
     *
     * @mbggenerated
     */
    public void setVipBirthDay(Integer vipBirthDay) {
        this.vipBirthDay = vipBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_IsLimit
     *
     * @return the value of t_vip_info.vip_IsLimit
     *
     * @mbggenerated
     */
    public String getVipIslimit() {
        return vipIslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_IsLimit
     *
     * @param vipIslimit the value for t_vip_info.vip_IsLimit
     *
     * @mbggenerated
     */
    public void setVipIslimit(String vipIslimit) {
        this.vipIslimit = vipIslimit == null ? null : vipIslimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baby1_name
     *
     * @return the value of t_vip_info.baby1_name
     *
     * @mbggenerated
     */
    public String getBaby1Name() {
        return baby1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baby1_name
     *
     * @param baby1Name the value for t_vip_info.baby1_name
     *
     * @mbggenerated
     */
    public void setBaby1Name(String baby1Name) {
        this.baby1Name = baby1Name == null ? null : baby1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baby1_birth_flag
     *
     * @return the value of t_vip_info.baby1_birth_flag
     *
     * @mbggenerated
     */
    public String getBaby1BirthFlag() {
        return baby1BirthFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baby1_birth_flag
     *
     * @param baby1BirthFlag the value for t_vip_info.baby1_birth_flag
     *
     * @mbggenerated
     */
    public void setBaby1BirthFlag(String baby1BirthFlag) {
        this.baby1BirthFlag = baby1BirthFlag == null ? null : baby1BirthFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baby1_birth_year
     *
     * @return the value of t_vip_info.baby1_birth_year
     *
     * @mbggenerated
     */
    public Integer getBaby1BirthYear() {
        return baby1BirthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baby1_birth_year
     *
     * @param baby1BirthYear the value for t_vip_info.baby1_birth_year
     *
     * @mbggenerated
     */
    public void setBaby1BirthYear(Integer baby1BirthYear) {
        this.baby1BirthYear = baby1BirthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baby1_birth_month
     *
     * @return the value of t_vip_info.baby1_birth_month
     *
     * @mbggenerated
     */
    public Integer getBaby1BirthMonth() {
        return baby1BirthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baby1_birth_month
     *
     * @param baby1BirthMonth the value for t_vip_info.baby1_birth_month
     *
     * @mbggenerated
     */
    public void setBaby1BirthMonth(Integer baby1BirthMonth) {
        this.baby1BirthMonth = baby1BirthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baby1_birth_day
     *
     * @return the value of t_vip_info.baby1_birth_day
     *
     * @mbggenerated
     */
    public Integer getBaby1BirthDay() {
        return baby1BirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baby1_birth_day
     *
     * @param baby1BirthDay the value for t_vip_info.baby1_birth_day
     *
     * @mbggenerated
     */
    public void setBaby1BirthDay(Integer baby1BirthDay) {
        this.baby1BirthDay = baby1BirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.update_time
     *
     * @return the value of t_vip_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.update_time
     *
     * @param updateTime the value for t_vip_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.update_branch
     *
     * @return the value of t_vip_info.update_branch
     *
     * @mbggenerated
     */
    public String getUpdateBranch() {
        return updateBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.update_branch
     *
     * @param updateBranch the value for t_vip_info.update_branch
     *
     * @mbggenerated
     */
    public void setUpdateBranch(String updateBranch) {
        this.updateBranch = updateBranch == null ? null : updateBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.recom_vip_no
     *
     * @return the value of t_vip_info.recom_vip_no
     *
     * @mbggenerated
     */
    public String getRecomVipNo() {
        return recomVipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.recom_vip_no
     *
     * @param recomVipNo the value for t_vip_info.recom_vip_no
     *
     * @mbggenerated
     */
    public void setRecomVipNo(String recomVipNo) {
        this.recomVipNo = recomVipNo == null ? null : recomVipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_not_sms
     *
     * @return the value of t_vip_info.vip_not_sms
     *
     * @mbggenerated
     */
    public String getVipNotSms() {
        return vipNotSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_not_sms
     *
     * @param vipNotSms the value for t_vip_info.vip_not_sms
     *
     * @mbggenerated
     */
    public void setVipNotSms(String vipNotSms) {
        this.vipNotSms = vipNotSms == null ? null : vipNotSms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.baoxian_yx_date
     *
     * @return the value of t_vip_info.baoxian_yx_date
     *
     * @mbggenerated
     */
    public Date getBaoxianYxDate() {
        return baoxianYxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.baoxian_yx_date
     *
     * @param baoxianYxDate the value for t_vip_info.baoxian_yx_date
     *
     * @mbggenerated
     */
    public void setBaoxianYxDate(Date baoxianYxDate) {
        this.baoxianYxDate = baoxianYxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.nianjian_yx_date
     *
     * @return the value of t_vip_info.nianjian_yx_date
     *
     * @mbggenerated
     */
    public Date getNianjianYxDate() {
        return nianjianYxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.nianjian_yx_date
     *
     * @param nianjianYxDate the value for t_vip_info.nianjian_yx_date
     *
     * @mbggenerated
     */
    public void setNianjianYxDate(Date nianjianYxDate) {
        this.nianjianYxDate = nianjianYxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.vip_web_pwd
     *
     * @return the value of t_vip_info.vip_web_pwd
     *
     * @mbggenerated
     */
    public String getVipWebPwd() {
        return vipWebPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.vip_web_pwd
     *
     * @param vipWebPwd the value for t_vip_info.vip_web_pwd
     *
     * @mbggenerated
     */
    public void setVipWebPwd(String vipWebPwd) {
        this.vipWebPwd = vipWebPwd == null ? null : vipWebPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.trans_upflag
     *
     * @return the value of t_vip_info.trans_upflag
     *
     * @mbggenerated
     */
    public String getTransUpflag() {
        return transUpflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.trans_upflag
     *
     * @param transUpflag the value for t_vip_info.trans_upflag
     *
     * @mbggenerated
     */
    public void setTransUpflag(String transUpflag) {
        this.transUpflag = transUpflag == null ? null : transUpflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_info.wx_openid
     *
     * @return the value of t_vip_info.wx_openid
     *
     * @mbggenerated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_info.wx_openid
     *
     * @param wxOpenid the value for t_vip_info.wx_openid
     *
     * @mbggenerated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }
}