package com.gd.data.mapper;


import com.gd.data.entity.TItemBrand;

import java.util.List;

public interface TItemBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_brand
     *
     * @mbggenerated
     */
    int insert(TItemBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_brand
     *
     * @mbggenerated
     */
    int insertSelective(TItemBrand record);

    List<TItemBrand> selectBrandList();
}