package com.gd.data.mapper;

import com.gd.data.entity.TItemInfo;
import com.gd.data.entity.TitemStock;
import com.gd.data.entity.TitemStockInfo;

import java.util.Date;
import java.util.List;

public interface TItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_info
     *
     * @mbggenerated
     */
    int insert(TItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_info
     *
     * @mbggenerated
     */
    int insertSelective(TItemInfo record);

    List<TitemStockInfo> selectItemInfo(Date date);

    List<TitemStock> selectTitemStock();
}