package com.gd.data.mapper;

import com.gd.data.entity.TOrderDetail;
import com.gd.data.entity.TPosSale;
import com.gd.data.entity.TPosSaleMaster;

import javax.xml.crypto.Data;
import java.util.Date;
import java.util.List;

public interface TPosSaleMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pos_sale_master
     *
     * @mbggenerated
     */
    int insert(TPosSaleMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pos_sale_master
     *
     * @mbggenerated
     */
    int insertSelective(TPosSaleMaster record);

    List<TPosSale> selectSaleDetail(Date date);

    List<TOrderDetail> selectOrderDetail(Date date);
}