package com.gd.data.mapper;

import com.gd.data.entity.TPosSaleDetail;

public interface TPosSaleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pos_sale_detail
     *
     * @mbggenerated
     */
    int insert(TPosSaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pos_sale_detail
     *
     * @mbggenerated
     */
    int insertSelective(TPosSaleDetail record);
}