package com.gd.data.mapper;

import com.gd.data.entity.TSupInfo;

import java.util.List;

public interface TSupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sup_info
     *
     * @mbggenerated
     */
    int insert(TSupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sup_info
     *
     * @mbggenerated
     */
    int insertSelective(TSupInfo record);

    List<TSupInfo> selectSupcust();
}