package com.gd.data.mapper;


import com.gd.data.entity.TSysUser;

import java.util.List;

public interface TSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated
     */
    int insert(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated
     */
    int insertSelective(TSysUser record);

    List<TSysUser> selectCashierList();

    List<TSysUser> selectSaleManList();
}