package com.gd.data.mapper;

import com.gd.data.entity.TVipInfo;

import java.util.List;

public interface TVipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_info
     *
     * @mbggenerated
     */
    int insert(TVipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_info
     *
     * @mbggenerated
     */
    int insertSelective(TVipInfo record);

    List<TVipInfo> selectVipInfo();
}