package com.gd.data.mapper;

import com.gd.data.entity.TVisaFlow;

import java.util.Date;
import java.util.List;

public interface TVisaFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visa_flow
     *
     * @mbggenerated
     */
    int insert(TVisaFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visa_flow
     *
     * @mbggenerated
     */
    int insertSelective(TVisaFlow record);

    List<TVisaFlow> selectVisaFlows(Date date);
}